var ArcDatabase = [
    {
        "﻿N°inventaire": "2 Fi 1",
        "Mode d'Acquisition": "Don de Grenko",
        "Descriptif": "2 Fi 1 - Grenko : 4 affiches couleur tirées  de la maquette réalisée pour la couverture du livre d’Yves Soulet « l’aventure sardinière » édité par les Amis de l’Ile de Noirmoutier (N° 5 de la collection « Noirmoutier à travers l’Histoire»",
        "Titre/Inscription": "Affiche",
        "Date d'Exécution": "2010",
        "Lieu": "Île de Noirmoutier",
        "Descriptif/Technique": "Lithographie couleur",
        "Dimensions ": "",
        "Auteur/Editeur": "Grenko, peintre comptemporainde Noirmoutier"
    },
    {
        "﻿N°inventaire": "2 Fi 2",
        "Mode d'Acquisition": "Don Juliane Bogaert",
        "Descriptif": "2 Fi 2   - Juliane Bogaert : Luzeronde - Marais et Esseps - Marais  salants sur l’ile de Noirmoutier - Maison en bordure du marais - le petit Vieil - marais  ",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "1981 - 1982",
        "Lieu": "Île de Noirmoutier",
        "Descriptif/Technique": "photocopies de Dessins",
        "Dimensions ": "37 cm x 30 cm",
        "Auteur/Editeur": "Juliane Bogaert  (Deux dessins originaux classés 3Fi 6 et 3Fi 5)"
    },
    {
        "﻿N°inventaire": "2 Fi 3",
        "Mode d'Acquisition": "Don Gilles Béranger Fonds 33 E",
        "Descriptif": "2 Fi 3  -Villa Les Louinas  au Bois de la Chaise - Groupe de personnages dont Pierre Hubert - Le château vu du port - L’église et le château vue de l’entrée du port (1875 – JC) - la  Baie de Saint Pierre (Noirmoutier)",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "1876",
        "Lieu": "Île de Noirmoutier",
        "Descriptif/Technique": "photocopies de Dessins au crayon",
        "Dimensions ": "A4",
        "Auteur/Editeur": "J.C"
    },
    {
        "﻿N°inventaire": "2 Fi 4",
        "Mode d'Acquisition": "Don Gilles Béranger Fonds 33 E  Classé Fonds Béranger",
        "Descriptif": "2 Fi 4 -  Coupures de presse \"Noirmoutier l'Île aux patates\"",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "1941",
        "Lieu": "Île de Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "A4",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 5",
        "Mode d'Acquisition": "Don Maurice Quenet",
        "Descriptif": "2 Fi 5 - Brevet de capitaine de la marine marchande décerné à Théodore Auguste Adrien",
        "Titre/Inscription": "Brevet de la marine marchande",
        "Date d'Exécution": "07/01/1923",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Papier",
        "Dimensions ": "40 x 26 cm",
        "Auteur/Editeur": "Imprimerie de la Marine Marchande"
    },
    {
        "﻿N°inventaire": "2 Fi 6",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 6 - « La Vie Illustrée » : Le submersible « Pluviose » coulé devant Calais par le paquebot « Pas de Calais »",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "4 juin 1910",
        "Lieu": "Calais",
        "Descriptif/Technique": "papier",
        "Dimensions ": "36 x 28 cm",
        "Auteur/Editeur": "Société anonyme des imprimeries Wellhoff rue notre-Dames-des-Victoires, Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 7",
        "Mode d'Acquisition": "Don Jacques Lechardour                Grand Père de Joseph Aimé",
        "Descriptif": "Société de Secours Mutuels. Nomination de Joseph Aimé Léchardour  comme membre participant",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "1er Avril 1895",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "",
        "Dimensions ": "43 x 30 cm",
        "Auteur/Editeur": "Imprimerie Paul Dupont.  Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 8",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi  8 - « La Vie Illustrée » : Journal hebdomadaire. Article sur Victor Hugo Figaro-salon et sur les funérailles d'Edouard VII",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "28 mai 1910  ",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier",
        "Dimensions ": "27,5 x 36 cm",
        "Auteur/Editeur": "Société anonyme des imprimeries Wellhoff rue notre-Dames-des-Victoires, Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 9",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 9 -  Planche de 18 images de réclame du «  Chocolates JAIME  BOIX » Barcelona : Guerre au  Japon",
        "Titre/Inscription": "image de guerre",
        "Date d'Exécution": "",
        "Lieu": "Japon",
        "Descriptif/Technique": "Images collées sur papier cartonné Impression couleur",
        "Dimensions ": "31 x 42 cm",
        "Auteur/Editeur": "Editeur Chantecler Collection D Van Treeck"
    },
    {
        "﻿N°inventaire": "2 Fi 10",
        "Mode d'Acquisition": "Don Bernard Martineau Noirmoutier, fonds 150 E 103",
        "Descriptif": "2 Fi 10 –  Affiche en couleur de l’usine Cassegrain Père et Fils à Noirmoutier",
        "Titre/Inscription": "Affiche",
        "Date d'Exécution": "vers 1950",
        "Lieu": "l’Herbaudière à Noirmoutier",
        "Descriptif/Technique": "papier - Chromo graphie",
        "Dimensions ": "42 x 29.5 cm",
        "Auteur/Editeur": "imprimerie moderne  Nantes "
    },
    {
        "﻿N°inventaire": "2 Fi 11",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 11 - Médaille d'honneur de la marine marchande attribué à Victor Adrien patron pêcheur inscrit aux Sables d'Olonne. Sous verre encadré illustré",
        "Titre/Inscription": "Diplôme de la marine marchande",
        "Date d'Exécution": "14 juillet 1932",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier",
        "Dimensions ": "50 x 40 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 12",
        "Mode d'Acquisition": "Don Jean Coulon de l’Epine, fonds169 E ",
        "Descriptif": "2 Fi 12– Diplôme d’honneur de Conseiller Municipal de Noirmoutier décerné à Denis Guillet         ",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "4 mai 1884",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier - Chromolithographie avec inscriptions manuscrites et cachet incrusté",
        "Dimensions ": "57 x 40 cm",
        "Auteur/Editeur": "Imprimerie Jehenne $ Cie"
    },
    {
        "﻿N°inventaire": "2 Fi 13",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 13 – Calendrier illustré par des reproductions d’aquarelles du peintre  Lumières de Morlaine  -installé dans la presqu'île guérandaise (né à Nantes en 1953)",
        "Titre/Inscription": "Paysage",
        "Date d'Exécution": "1997",
        "Lieu": "côte de Noirmoutier à belle ile",
        "Descriptif/Technique": "Lithographie",
        "Dimensions ": "49 x 41 cm",
        "Auteur/Editeur": "imprimerie du Lion 90700 Châtenois-les-Forges "
    },
    {
        "﻿N°inventaire": "2 Fi 14",
        "Mode d'Acquisition": "Cadeau fait à Claude Bouhier par le Dr Paul Nicaud",
        "Descriptif": "2 Fi 14 – Six reproductions animalières",
        "Titre/Inscription": "Thème de la chasse",
        "Date d'Exécution": "édition 2001 ",
        "Lieu": "",
        "Descriptif/Technique": "reproductions couleur",
        "Dimensions ": "43 x 30 cm",
        "Auteur/Editeur": "le Chasseur Français"
    },
    {
        "﻿N°inventaire": "2 Fi 15",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 15 - Le petit journal illustré  n° spécial avec signatures des protagonistes sur l’armistice de la guerre 1914-1918 – Article de Marc Langlais sur Clemenceau \"Le Tigre en pantoufles\"",
        "Titre/Inscription": "Presse militaire",
        "Date d'Exécution": "Supplément du 27 juillet 1919 ",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier - Impression noir et blanc et couleur",
        "Dimensions ": "39 x 31 cm",
        "Auteur/Editeur": "imprimé à Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 16",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 16 – Diplôme de  Communion Solennelle remis à Charles Adrien, baptisé le 21 mai 1925     -  Représentation de scènes de la vie Religieuse",
        "Titre/Inscription": "Diplôme religieux",
        "Date d'Exécution": "7 juin 1936",
        "Lieu": "Ile de Noirmoutier ",
        "Descriptif/Technique": "papier cartonné - Chromolithographie",
        "Dimensions ": "46 x 30 cm",
        "Auteur/Editeur": "Bouasse Jeune Paris "
    },
    {
        "﻿N°inventaire": "2 Fi 17",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 17 -  Diplôme de  Communion Solennelle remis à Auguste Ganachaud, baptisé le 25 octobre 1903   -  Scènes de la vie religieuse ",
        "Titre/Inscription": "Diplôme religieux",
        "Date d'Exécution": "7 juin 1914",
        "Lieu": "Paroisse Saint Jean Baptiste de L’Epine, île de Noirmoutier ",
        "Descriptif/Technique": "papier Chromolithographie",
        "Dimensions ": "46 x 30 cm",
        "Auteur/Editeur": "Bouasse Jeune Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 18",
        "Mode d'Acquisition": "Fonds Gaby Soulard Don",
        "Descriptif": "2 Fi 18 –Diplôme de Communion Solennelle remis à Véronique Fourage, baptisée le 20 mai 1910   - Scènes de la vie religieuse ",
        "Titre/Inscription": "Diplôme religieux",
        "Date d'Exécution": "26 mai 1921  ",
        "Lieu": "Barbâtre, île de Noirmoutier ",
        "Descriptif/Technique": "papier- Chromolithographie",
        "Dimensions ": "46 x 30 cm",
        "Auteur/Editeur": "Bouasse Lebel Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 19",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 19 -  Diplôme de Communion solennelle remis à Léonore Sévère Couthuis  - Image pieuse représentant des scènes de la vie religieuse",
        "Titre/Inscription": "Diplôme religieux",
        "Date d'Exécution": "24  juin 1882",
        "Lieu": "L’Epine Ile de  Noirmoutier ",
        "Descriptif/Technique": "papier -Lithographie",
        "Dimensions ": "46 x 31 cm",
        "Auteur/Editeur": "Chassagnot Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 20",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 20 -  Image pieuse représentant le Christ Cor Jesu Sacratissimum",
        "Titre/Inscription": "Image pieuse",
        "Date d'Exécution": "",
        "Lieu": "",
        "Descriptif/Technique": "papier -Lithographie",
        "Dimensions ": "27 x 16 cm",
        "Auteur/Editeur": "Bouasse Lebel Paris "
    },
    {
        "﻿N°inventaire": "2 Fi 21",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 21  – Mission  à l’Epine Île de Noirmoutier  -  Vierge à l’enfant",
        "Titre/Inscription": "Affiche religieuse",
        "Date d'Exécution": "2 au 25 décembre 1934",
        "Lieu": "Paroisse de l’Epine",
        "Descriptif/Technique": "papier cartonné - Lithographie",
        "Dimensions ": "42 x 30 cm",
        "Auteur/Editeur": "Imprimerie Renolleau – Morin La-Roche-sur-Yon"
    },
    {
        "﻿N°inventaire": "2 Fi 22",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2Fi 22 - Mission du Vieil 13-27 Novembre 1938   Abbé Billaud  Chapelin ",
        "Titre/Inscription": "Affiche religieuse",
        "Date d'Exécution": "Novembre 1938",
        "Lieu": "Paroise du Vieil",
        "Descriptif/Technique": "Papier Cartonné",
        "Dimensions ": "28 x 38 cm",
        "Auteur/Editeur": "Imprimrie moderne Fontenay le Comte"
    },
    {
        "﻿N°inventaire": "2 Fi 23",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi 23 - Diplôme de mérite  pour l’année scolaire 1914-1915 décerné à François Fouasson  - Récompense",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "24 juillet 1915",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier- Lithographie",
        "Dimensions ": "29 x 22 cm",
        "Auteur/Editeur": "L'Ecole   Rue des Saints Pères  PARIS"
    },
    {
        "﻿N°inventaire": "2 Fi 24",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi 24 - Certificat d’études primaires délivré à François Fouasson né le 9 juin 1908 à Noirmoutier -  ",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "15 juillet 1920 ",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier- Polychromie",
        "Dimensions ": "38 x 28 cm",
        "Auteur/Editeur": "Inspection académique du département de la Vendée   Imprimeur : Roche-Jourdain"
    },
    {
        "﻿N°inventaire": "2 Fi 25",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi 25 - Certificat d’instruction Agricole Primaire décerné à François Fouasson élève à l’école libre de Noirmoutier",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "10 juillet 1920",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": " papier- Lithographie",
        "Dimensions ": "40,2 x 32 cm",
        "Auteur/Editeur": "Imprimerie Servant-Mahaud "
    },
    {
        "﻿N°inventaire": "2 Fi 26",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi 26 - Diplôme d’enseignement agricole décerné à François Fouasson étudiant à Noirmoutier",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "23 juin1921",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier-  Lithographie",
        "Dimensions ": "58 x 45 cm : ",
        "Auteur/Editeur": "Syndicat des agriculteurs de Vendée"
    },
    {
        "﻿N°inventaire": "2 Fi 27",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi  27  -  Diplôme du concours général de la région de l’ouest décerné à François Fouasson étudiant à Saint Gabriel, Saint Laurent sur Sèvre   -   Diplôme de fin d’études",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "29 juin 1925",
        "Lieu": "Angers",
        "Descriptif/Technique": "papier-  Lithographie",
        "Dimensions ": "43 x 32 cm",
        "Auteur/Editeur": "Imprimeur            Grassin et Lecoq"
    },
    {
        "﻿N°inventaire": "2 Fi 28",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi  28 -  Certificat d’instruction chrétienne primaire et supérieur décerné à François Fouasson par l’évêque de Luçon  Gustave Lazare ",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier-  Lithographie",
        "Dimensions ": "56 x 38 cm",
        "Auteur/Editeur": "Imprimeur : Gallet Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 29",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi  29 -  Certificat d’études primaires décerné à Anne Fouasson née le 26 juillet 1904 élève à Noirmoutier",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "19 juin 1916",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier-  Lithographie",
        "Dimensions ": "37 x 28 cm",
        "Auteur/Editeur": "Imprimerie Roche-Jourdain"
    },
    {
        "﻿N°inventaire": "2 Fi 30",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi 30 – Diplôme de mérite scolaire décerné à Anne Fouassonnée , élève de l’école libre de Noirmoutier pour l'année scolaire 1914-1915",
        "Titre/Inscription": " Diplôme scolaire",
        "Date d'Exécution": "24 juillet 1915",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier- Polychromie",
        "Dimensions ": "39 x 32 cm",
        "Auteur/Editeur": "L’Ecole Paris "
    },
    {
        "﻿N°inventaire": "2 Fi 31",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi 31 -  Certificat d’enseignement ménager décerné à Anne Fouasson Ecole Libre de Noirmoutier",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": "7 juin 1917",
        "Lieu": "La Roche sur Yon",
        "Descriptif/Technique": "papier- lithographie",
        "Dimensions ": "51 x 41 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 32",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 55 E",
        "Descriptif": "2 Fi 32 - Image délivrée à François Fouasson  en souvenir de sa première communion, 15 juin 1919   -  le curé est Robert",
        "Titre/Inscription": "Image religieuse",
        "Date d'Exécution": "15 juin 1919",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier-  polychromie",
        "Dimensions ": "29 x 44 cm",
        "Auteur/Editeur": "Bouasse le Bel Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 33",
        "Mode d'Acquisition": "Achat",
        "Descriptif": "2 Fi 33 - Affiche du gouverneur militaire de Paris Gallieni  -  Profession de foi  de Gallieni proclamant son intention de défendre Paris jusqu’au bout de son mandat.",
        "Titre/Inscription": " Affiche militaire",
        "Date d'Exécution": "3 septembre 1914 ",
        "Lieu": " Paris",
        "Descriptif/Technique": "papier -Lithographie",
        "Dimensions ": "84 x 49 cm",
        "Auteur/Editeur": "Marcel picard 140 rue du Faubourg Saint Martin"
    },
    {
        "﻿N°inventaire": "2 Fi 34",
        "Mode d'Acquisition": "Don François Boisson",
        "Descriptif": "2 Fi 34 - Commard de Puylorson: \"Messire andré commard de puylorsson né en  noirmoutier en 1710 pretre docteur en théologie chanoine de l’eglise royale de guérande en 1746\"",
        "Titre/Inscription": "Portrait",
        "Date d'Exécution": "XVIIIe siècle",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Reproduction d’une peinture",
        "Dimensions ": "38 x 53 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 35",
        "Mode d'Acquisition": "Don Chebret",
        "Descriptif": "4 crayons de Vincent-Darasse illustrant des pages de la revue \"Les côtes de de France\"",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "XXe siècle",
        "Lieu": "Ile de Noirmoutier",
        "Descriptif/Technique": "reproduction de dessins au crayon",
        "Dimensions ": "16 x 26 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 36",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 36 - Plages du Bois de la Chaise  Parmi les puis belles plages de France Jolis Chalets à Vendre  ou à Louer",
        "Titre/Inscription": "Affiche publicitaire",
        "Date d'Exécution": "",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "impression N.B.",
        "Dimensions ": "38 x 80 cm",
        "Auteur/Editeur": "Imprimerie du Progrès. Nantes"
    },
    {
        "﻿N°inventaire": "2 Fi 37",
        "Mode d'Acquisition": "Reproduction faite par l'AAIN",
        "Descriptif": "2 Fi 37 – Trente  photocopies de la gravure des 12 vendéens qui a servi à faire la couverture de la Lettre aux Amis  n°",
        "Titre/Inscription": "Document historique",
        "Date d'Exécution": "XIXe siècle",
        "Lieu": "Paris",
        "Descriptif/Technique": "Impression couleur",
        "Dimensions ": "35 x 25 cm",
        "Auteur/Editeur": "imprimerie Gaultier. Chantonnay "
    },
    {
        "﻿N°inventaire": "2 Fi 38",
        "Mode d'Acquisition": " Achat à R I C M B",
        "Descriptif": "2 Fi 38 -Reproduction d'aquarelles de Dany Cayzac faite pour l’association R I C M B  -  En souvenir des officiers canadiens  morts lors du bombardement des 4 As dans le goulet de Fromentine",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "XXe siècle",
        "Lieu": "Barbâtre",
        "Descriptif/Technique": "Reproduction d'aquarelles",
        "Dimensions ": "74 x 13 cm",
        "Auteur/Editeur": "Dany Caysac"
    },
    {
        "﻿N°inventaire": "2 Fi 39",
        "Mode d'Acquisition": " Don de Mr Lemoing de Genève",
        "Descriptif": "2 Fi 39 -  Carte de vœux représentant un tableau de Pierre-Auguste Renoir (1841-1919)    ",
        "Titre/Inscription": "Paysage",
        "Date d'Exécution": "1892",
        "Lieu": "le Bois de la Chaise à Noirmoutier",
        "Descriptif/Technique": "papier cartonné Reproduction couleur d’un tableau de Renoir  propriété de la fondation Barnes 1994",
        "Dimensions ": "18 x 13 cm",
        "Auteur/Editeur": "Graphique de France, Boston, Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 40",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 40 -  \" Les généraux du Sacré-cœur\" Portrait de Charette de la Contrie tiré de la revue Le Pèlerin n° 559 d'après une gravure de Guérin",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "Révolution Française",
        "Lieu": "Vendée militaire",
        "Descriptif/Technique": "impression N.B.",
        "Dimensions ": "27 x 18 cm",
        "Auteur/Editeur": "Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 41",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2Fi 41 - Certificat de bonne conduite délivré à Jean Pineau par le capitaine Bigeard de la base aérienne de Tours",
        "Titre/Inscription": "Diplôme professionnel",
        "Date d'Exécution": "1967",
        "Lieu": "Tours",
        "Descriptif/Technique": "papier cartonné",
        "Dimensions ": "32 x 25 cm",
        "Auteur/Editeur": "Imprimerie Chotel  Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 42",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 42 – Diplôme de la police municipale décerné à Jules Robin   -  Récompense",
        "Titre/Inscription": "Diplôme professionnel",
        "Date d'Exécution": "1903",
        "Lieu": "Bouin",
        "Descriptif/Technique": "papier - Lithographie",
        "Dimensions ": "57 x 44 cm",
        "Auteur/Editeur": "Imprimerie Ch Wittmann Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 43",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 43 -  Diplôme  illustré décerné à Jules Robin, Garde champêtre",
        "Titre/Inscription": "Diplôme professionnel",
        "Date d'Exécution": "7 juin 1914",
        "Lieu": "Bouin",
        "Descriptif/Technique": "papier - Lithographie avec personnages de fonction",
        "Dimensions ": "56 x 44 cm",
        "Auteur/Editeur": "Imprimerie Feuillet Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 44",
        "Mode d'Acquisition": "Don Jean Coulon de l'Epine",
        "Descriptif": "2 Fi 44 -  Diplôme illustré commémoratif dédié à Mr Guillet    -  2e prix du concours agricole avec prime de 45 francs",
        "Titre/Inscription": "Diplôme agricole",
        "Date d'Exécution": "1912",
        "Lieu": "Machecoul",
        "Descriptif/Technique": "papier - Lithographie",
        "Dimensions ": "54 x 44 cm",
        "Auteur/Editeur": "Larbalétrier imprimerie Feuillet Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 45",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 45 – Brevet d'aptitude attribué à Maurice Roger Baud  ",
        "Titre/Inscription": "Diplôme de la marine ",
        "Date d'Exécution": "21 juin 1937",
        "Lieu": "Bordeaux",
        "Descriptif/Technique": "papier -Lithographie",
        "Dimensions ": "26 x 37 cm",
        "Auteur/Editeur": "Graveur marine marchande"
    },
    {
        "﻿N°inventaire": "2 Fi 46",
        "Mode d'Acquisition": "Don Frapereau janvier 1983",
        "Descriptif": "2 Fi 46 -  Diplôme de la Compagnie Générale Transatlantique, médaille d’argent   -  Reconnaissance pour la conduite héroïque du matelot Raguideau lors de l’incendie à bord du Lafayette",
        "Titre/Inscription": "Diplôme de la marine",
        "Date d'Exécution": "1900",
        "Lieu": "",
        "Descriptif/Technique": "Topographie d’un dessin à la pointe sèche",
        "Dimensions ": "45 x 41 cm",
        "Auteur/Editeur": "A. Lemercier"
    },
    {
        "﻿N°inventaire": "2 Fi 47",
        "Mode d'Acquisition": "Don Clement Corbrejaud",
        "Descriptif": "2 Fi 47 -  Brevet d'aptitude de nageur de demi-fond, 500 mètres, délivré au matelot Jean Thibaud par Fédération Nationale de sauvetage",
        "Titre/Inscription": "Diplôme sportif",
        "Date d'Exécution": "23 septembre 1935",
        "Lieu": "",
        "Descriptif/Technique": "papier - Photocopie",
        "Dimensions ": "30 x 42 cm",
        "Auteur/Editeur": "Saint Jean de Luz"
    },
    {
        "﻿N°inventaire": "2 Fi 48",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 48 - Diplôme de fin d'études au Brevet d’infirmier décerné à Pierre François Ganachaud  -  Au verso notes de l’élève au brevet",
        "Titre/Inscription": "Diplôme professionnel",
        "Date d'Exécution": "1890",
        "Lieu": "",
        "Descriptif/Technique": "papier - Lithographie",
        "Dimensions ": "24 x 31cm",
        "Auteur/Editeur": "Paul Dupont pour la marine "
    },
    {
        "﻿N°inventaire": "2 Fi 49",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 49 – Médaille d’honneur de la Marine Marchande décerné à Pierre-François Ganachaud matelot inscrit aux Sables d’Olonne",
        "Titre/Inscription": "Diplôme de la marine",
        "Date d'Exécution": "16 juillet 1932",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier - Lithographie illustrée d'un bateau",
        "Dimensions ": "56 x 38 cm",
        "Auteur/Editeur": " Michel"
    },
    {
        "﻿N°inventaire": "2 Fi 50",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 50 - Journal « Figaro-Salon »   -   recueil de gravures diverses",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "1885",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier - Typographie",
        "Dimensions ": "32 x 42 cm",
        "Auteur/Editeur": "Typo gravure Boussod, Valadon et Cie"
    },
    {
        "﻿N°inventaire": "20Fi 51",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 51 – Mission paroisse de Saint Philbert   -   portrait du Christ",
        "Titre/Inscription": "Affiche religieuse",
        "Date d'Exécution": "2 au 25 décembre 1934",
        "Lieu": "Noirmoutier en l’ile",
        "Descriptif/Technique": "papier- Reprogravure",
        "Dimensions ": "38 x 27 cm",
        "Auteur/Editeur": "Propriété de \"L'apôtre du Foyer\" Imprimerie J. Le Hénaff"
    },
    {
        "﻿N°inventaire": "2 Fi 52",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 52 - Mission paroisse de Saint Philbert   -   Vierge à l’enfant",
        "Titre/Inscription": "Affiche religieuse",
        "Date d'Exécution": "5 au 26 decembre 1926",
        "Lieu": "Noirmoutier en l’ile",
        "Descriptif/Technique": "papier- Reproduction couleur",
        "Dimensions ": "39 cm x 29 cm",
        "Auteur/Editeur": "librairie J. Baudry la Roche sur Yon "
    },
    {
        "﻿N°inventaire": "2 Fi 53",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi  53 -  Image pieuse de la sainte vierge   -   Vierge à l’enfant",
        "Titre/Inscription": "Image pieuse",
        "Date d'Exécution": "",
        "Lieu": "",
        "Descriptif/Technique": "papier cartonné- reproduction",
        "Dimensions ": "33 x 24 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 54",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds  55 E",
        "Descriptif": "2 Fi 54 - Diplôme d'honneur décerné à Marcel Fradet: Le devoir social  - Pour la reconstitution des foyers détruits par la guerre",
        "Titre/Inscription": "Diplôme militaire",
        "Date d'Exécution": "12 juillet 1920",
        "Lieu": "Machecoul",
        "Descriptif/Technique": "papier- gravure",
        "Dimensions ": "37 x 27 cm",
        "Auteur/Editeur": "Charles Foucray  1917. Imprimeur Lapina Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 55",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds 55 E",
        "Descriptif": "2 Fi 55 -  Diplôme d’honneur Illustré  décerné à Marcel Fradet de l'école de Machecoul.  Comptez sur nous mes chères petites",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": "31 décembre 1920",
        "Lieu": "Machecoul",
        "Descriptif/Technique": "papier",
        "Dimensions ": "30x27 cm",
        "Auteur/Editeur": "Dessin d'Henri Royer"
    },
    {
        "﻿N°inventaire": "2 Fi  56",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 56 - Certificat d'instruction Agricole primaire de Pierre Gendron ",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": "2 juin 1932",
        "Lieu": "La-Roche-sur-Yon",
        "Descriptif/Technique": "papier",
        "Dimensions ": "30 x 40 cm",
        "Auteur/Editeur": "Imprimerie Grillard"
    },
    {
        "﻿N°inventaire": "2 Fi 57",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 57 - Certificat d'instruction primaire décerné à Pierre Gendron",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": "22/06/1932",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "30 x 40 cm",
        "Auteur/Editeur": "Imprimerie G. Grillard. La Roche-sur-Yon"
    },
    {
        "﻿N°inventaire": "2 Fi   58 ",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds 55 E",
        "Descriptif": "2 Fi   58 – acte de communion solennelle de Marie Alphonsine Friou.  Signé par le curé Rouflet",
        "Titre/Inscription": "Diplôme religieux",
        "Date d'Exécution": "",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "44 x 28 cm",
        "Auteur/Editeur": "Boumard éditeurs pontificaux"
    },
    {
        "﻿N°inventaire": "2 Fi 59 (1)",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds 55 E",
        "Descriptif": "2 Fi 59 (1)– Diplôme d’honneur et insigne d’honneur décerné à Pierre Lointier pour un sauvetage sur la  Loire   -  décerné par la Société des Hospitaliers Sauveteurs Bretons",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "13 juin 1957",
        "Lieu": "Rennes",
        "Descriptif/Technique": "papier",
        "Dimensions ": "40 x 27cm",
        "Auteur/Editeur": "Les imprimeurs réunis à Rennes"
    },
    {
        "﻿N°inventaire": "2 Fi 59 (2)",
        "Mode d'Acquisition": "Don  Maurice Quenet 55 E",
        "Descriptif": "2 Fi 59 (2)-  Mention honorable décernée à Pierre Lointier pour le sauvetage qu’il a effectué sur la Loire -Naufrage à Saint Nazaire",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "2 septembre 1957",
        "Lieu": "Loire Atlantique",
        "Descriptif/Technique": "papier",
        "Dimensions ": "42 x 27 cm",
        "Auteur/Editeur": " Editeur : Ministère de la Marine à Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 60 ",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds 55 E",
        "Descriptif": "2 Fi 60  - Médaille militaire  de grand chancelier de la légion d’honneur décerné à Philbert Alphonse Moizeau Noirmoutier gendarme à la 11e légion de gendarmerie",
        "Titre/Inscription": "Diplôme militaire",
        "Date d'Exécution": "23-juin-22",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "48 x 36 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 61 ",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds 1455 E",
        "Descriptif": "2 Fi 61  -  Médaille militaire décerné à Théodore Auguste Adrien ",
        "Titre/Inscription": "Diplôme militaire",
        "Date d'Exécution": "4 octobre 1938",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "48 x 36 cm",
        "Auteur/Editeur": "Editeur ministère de la Marine"
    },
    {
        "﻿N°inventaire": "2 Fi 62 ",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds 55 E",
        "Descriptif": "2 Fi 62  -  74 Diplôme décerné aux soldats morts pour la France attribué à Fernand Ernest Adrien   -  Diplôme édité par la loi du 27 avril 1916. Imprimé chez Goupil",
        "Titre/Inscription": "Diplôme militaire 1914-1918",
        "Date d'Exécution": "mort pour la France le 10 octobre 1917",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "53 x 34 cm",
        "Auteur/Editeur": " Composé et gravé par CH. COppier. Imprimerie Goupil"
    },
    {
        "﻿N°inventaire": "2 Fi 63",
        "Mode d'Acquisition": "Don Furger Fonds  80 E",
        "Descriptif": "2 Fi 63 83 -  Médaille d’Honneur du travail décerné à Henri Louis Robin maçon poseur dans l’entreprise Lafontaine à Noirmoutier",
        "Titre/Inscription": "Diplôme civil",
        "Date d'Exécution": "1 décembre 1901",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier- Lithographie",
        "Dimensions ": "31 x 40 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "20Fi 64",
        "Mode d'Acquisition": "Don Furger Fonds 80 E",
        "Descriptif": "2 Fi 64 - Diplôme de communion solennelle décerné à Henri Furger baptisé le 2 novembre 1908   -   le prêtre est Robert",
        "Titre/Inscription": "Diplôme religieux",
        "Date d'Exécution": "18 juin1916",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier- polychromie",
        "Dimensions ": "45 x 30 cm",
        "Auteur/Editeur": "Bouasse jeune Paris distribué par la librairie Braudry La Roche sur Yon"
    },
    {
        "﻿N°inventaire": "2 Fi 65",
        "Mode d'Acquisition": "Don Furger Fonds 80 E",
        "Descriptif": "2 Fi 65  -  Diplôme de communion solennelle décerné à Jean Furger baptisé le 3 mai 1917",
        "Titre/Inscription": "Diplôme religieux",
        "Date d'Exécution": "3 juin 1928",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "polichromie le curé est Lebreton",
        "Dimensions ": "45 x 30 cm",
        "Auteur/Editeur": "Bouasse jeune Paris distribué par la librairie Braudry La Roche sur Yon"
    },
    {
        "﻿N°inventaire": "2 Fi 66",
        "Mode d'Acquisition": "Don Furger Fonds 80 E",
        "Descriptif": "2 Fi 66  - Mission décembre 1934",
        "Titre/Inscription": "Affiche religieuse",
        "Date d'Exécution": "",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier- polychromie",
        "Dimensions ": "38 x 30 cm",
        "Auteur/Editeur": "Propriété de l’apôtre du foyer imprimeur Le Hénaff § Cie"
    },
    {
        "﻿N°inventaire": "2 Fi 67",
        "Mode d'Acquisition": "Don Furger Fonds 80 E",
        "Descriptif": "2 Fi 67  - Mission de Saint Philbert de Noirmoutier",
        "Titre/Inscription": "Affiche religieuse",
        "Date d'Exécution": "5 au 26 décembre 1926 curé le Breton ",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier- polychromie",
        "Dimensions ": " 39x28 cm",
        "Auteur/Editeur": "Maison Hamann Amiens imprimerie Art couleur Lyon"
    },
    {
        "﻿N°inventaire": "2 Fi 68",
        "Mode d'Acquisition": "Don Furger Fonds 80 E",
        "Descriptif": "2 Fi 68 - Jeanne D’arc en armure. Reproduction couleur d'un tableau d'Ingres de 1854 qui se trouve  au Louvre",
        "Titre/Inscription": "Image historique",
        "Date d'Exécution": "1854",
        "Lieu": "",
        "Descriptif/Technique": "Papier - Reproduction couleur  ",
        "Dimensions ": "41 x30 cm",
        "Auteur/Editeur": "La maison de la Presse Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 69",
        "Mode d'Acquisition": "Don ",
        "Descriptif": "2 Fi 69 - 1 à 10 reproductions de dessins, d'aquarelles et de photos pour la revue l’Illustration concernant la guerre de 1914-1918   -    Scènes de guerre                      ",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "1914 - 1918",
        "Lieu": "Le Front",
        "Descriptif/Technique": "papier",
        "Dimensions ": "41 x 31 cm",
        "Auteur/Editeur": "Gervex, Lucien Jonas, A. De broca etc"
    },
    {
        "﻿N°inventaire": "2 Fi 70",
        "Mode d'Acquisition": "Don  Furger Fonds 80 E",
        "Descriptif": "2 Fi 70  -  Brevet de maître au Cabotage décerné à Jean-François Furger né le 3 décembre 1845 \"dela part de l'empereur\"",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "30 mai 1870",
        "Lieu": "Brevet enregistré à Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "25 x 39 cm",
        "Auteur/Editeur": "Marine,  administration centrale"
    },
    {
        "﻿N°inventaire": "2 Fi 71",
        "Mode d'Acquisition": "Don Furger Fonds 80 E",
        "Descriptif": "2 Fi 71  -Gravure commémorative dédiée à Henri Robin ancien combattant de la guerre 1870-1871 ",
        "Titre/Inscription": "Diplôme militaire",
        "Date d'Exécution": "Guerre 1870-1871",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier colorisée illustré",
        "Dimensions ": "63 x 45 cm",
        "Auteur/Editeur": "J. Chaffiol Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 72",
        "Mode d'Acquisition": "Don Furger Fonds 80 E ",
        "Descriptif": "2 Fi 72  - Médaille décerné à Louis Joseph Semelin  marin inscrit à Noirmoutier",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "10 février 1912 ",
        "Lieu": "Paris",
        "Descriptif/Technique": " papier- Chromolithographie",
        "Dimensions ": "51 x 31cm",
        "Auteur/Editeur": "CH. Marey. Gr tirage 1483 "
    },
    {
        "﻿N°inventaire": "2 Fi 73",
        "Mode d'Acquisition": "Don Gaby Soulard Fonds 51 E",
        "Descriptif": "2 Fi 73 - Supplément d’Hebdomadaire du vendredi de la revue Gil Blas   -   Caricature humoristique avec au verso de la feuille un pamphlet intitulé « La petite femme et le vieux juif »",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "8 janvier 1997",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier-  Chromolithographie",
        "Dimensions ": "38 x 27 cm",
        "Auteur/Editeur": "Dessiné par de Steinlein"
    },
    {
        "﻿N°inventaire": "2 Fi 74 ",
        "Mode d'Acquisition": "Don ? ",
        "Descriptif": "2 Fi 74 Portofolio de 25 reproductions de photographies des villes paysages et peintures célèbre rassemblées par John L. Stoddard",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "",
        "Lieu": "France ?",
        "Descriptif/Technique": "papier",
        "Dimensions ": " 34 x 48 cm",
        "Auteur/Editeur": "publié hebdomadairement par THE WERNER Coy Chicago imprimerie Lib-Imp. Reunies rue Mignon Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 75",
        "Mode d'Acquisition": "Don",
        "Descriptif": "8 Fi 75 Affiche exposition par les « les amis des arts » de Epaud – Bezu : Cinquante ans après exposition 1914-1918   -   ",
        "Titre/Inscription": " Affiche. Guerre 1914-1918",
        "Date d'Exécution": "vers 1964 - 1968 ",
        "Lieu": "Epaud - Bezu",
        "Descriptif/Technique": "papier- Affiche",
        "Dimensions ": "58 x 40cm",
        "Auteur/Editeur": "imprimeur du centre Ch Thierry"
    },
    {
        "﻿N°inventaire": "2 Fi 76",
        "Mode d'Acquisition": "Don Maurice Quenet  55 E",
        "Descriptif": "2 Fi 76 Chantiers de Saint Nazaire, la grande\"forme-écluse\" de construction au XIXe siècle: Lancement du cargo Tunisie (04/05/1951), du cuirassé Massena (24/07/1895), du paquebot mixte Claude Bernard",
        "Titre/Inscription": "Marine",
        "Date d'Exécution": "1895 et 1951",
        "Lieu": "Saint Nazaire",
        "Descriptif/Technique": "papier cartonné, reproduction couleur",
        "Dimensions ": "24 x 32 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 77 ",
        "Mode d'Acquisition": "Don Maurice Quenet  55 E",
        "Descriptif": "2 Fi 77 Le côtre bateau pilote Cariad, le brick Marie Sophie  (Allemagne), le trois mats goelette à huniers Result, le trois mats goelette Waterwitch 1879( England)",
        "Titre/Inscription": "Marine",
        "Date d'Exécution": "XIXe siècle",
        "Lieu": "Angleterre et Allemagne",
        "Descriptif/Technique": "papier cartonné, couleur ",
        "Dimensions ": "39 x 38 cm",
        "Auteur/Editeur": "Auteur: John garden. Editeur Hempel's Marine Paints avec l'autorisation de Hugh Evelyn, Londres"
    },
    {
        "﻿N°inventaire": "2 Fi 78",
        "Mode d'Acquisition": "Don de Maurice Quenet Fonds 55 E",
        "Descriptif": "2 Fi 78   - Trois mats terre neuvier de Granville \"le Precurseur\" par Marin Marie (1920), quatre mats\"L' Antonin\" de la campagne Bordes au Cap Horn (1913), Frégate (1830) par Marin Marie, Photo d'un navire hollandais du XVIIIe siècle",
        "Titre/Inscription": "Marine",
        "Date d'Exécution": "1920 - 1913 - 1830 - XVIIIe siècle",
        "Lieu": "France et Hollande",
        "Descriptif/Technique": "Reproduction couleur et photo",
        "Dimensions ": "40 x 30 cm",
        "Auteur/Editeur": "Marin Marie et photo Schiffen, mer calm"
    },
    {
        "﻿N°inventaire": "2 Fi  79",
        "Mode d'Acquisition": "Don Charley Garet Fonds 9 E",
        "Descriptif": "2 Fi 79 - Le Brick Frédéric\n\n",
        "Titre/Inscription": "Marine",
        "Date d'Exécution": "XIXe siècle",
        "Lieu": "",
        "Descriptif/Technique": "papier- Lithographie couleur",
        "Dimensions ": "41 x 50 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 80 ",
        "Mode d'Acquisition": "Don Mme Lemoing. Fonds",
        "Descriptif": "2 Fi 80  -  Exposition universelle de 1889, Diplôme obtenu par Cécile de Jansens pour le concours photographique.",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "Septembre 1889",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier",
        "Dimensions ": "58 x 43 cm",
        "Auteur/Editeur": "P.V. Galland graveur Ch Walter"
    },
    {
        "﻿N°inventaire": "2 Fi 81 ",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 81 -  Photo officielle du président de la République Française Paum Doumer",
        "Titre/Inscription": "Affiche",
        "Date d'Exécution": "",
        "Lieu": "",
        "Descriptif/Technique": "papier",
        "Dimensions ": "51 x37 cm",
        "Auteur/Editeur": "supplément à l’illustration du 20 juin 1931  photographe Gerschel"
    },
    {
        "﻿N°inventaire": "2 Fi 82 ",
        "Mode d'Acquisition": "Fonds Archambaud    53 E ",
        "Descriptif": "2 Fi 82  Ministère de l’intérieur : Médaille d’honneur des sapeurs-pompiers de Noirmoutier  décené à Charles Leroy",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": " 9 Juin 1903",
        "Lieu": "Paris",
        "Descriptif/Technique": "Papier",
        "Dimensions ": "33 x 41 cm",
        "Auteur/Editeur": "Provost- Blondel"
    },
    {
        "﻿N°inventaire": "2 Fi 83 ",
        "Mode d'Acquisition": "Achat 1984 ",
        "Descriptif": "2 Fi 83  -  Congé définitif 1er compagnie d’artillerie de la marine et des colonies pour Charles Leroy",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "31 décembre 1873",
        "Lieu": "Brest",
        "Descriptif/Technique": "",
        "Dimensions ": "42 x28 cm",
        "Auteur/Editeur": "Carré"
    },
    {
        "﻿N°inventaire": "2 Fi 84",
        "Mode d'Acquisition": "Don : M. Et Mme Paul Damour et Pellemelle Fonds 60 E",
        "Descriptif": "2 Fi 84  Certificat d’étude de Paul Abram né le 4 août 1893 à Noirmoutier",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "20 juillet 1906",
        "Lieu": "La Roche-sur-Yon ",
        "Descriptif/Technique": "papier",
        "Dimensions ": "37,5 x 28 cm",
        "Auteur/Editeur": " Graveur :      Roche Jourdain    la Roche sur Yon"
    },
    {
        "﻿N°inventaire": "2 Fi 85 ",
        "Mode d'Acquisition": "M. Et Mme Paul Damour et Pellemelle Fonds 60 E",
        "Descriptif": "2 Fi 85  -  Hommage de la nation délivré à Paul Abram mort pour la France le 6 septembre 1914",
        "Titre/Inscription": "Diplôme militaire Guerre 1914-1918",
        "Date d'Exécution": "1918",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "52  x 34 cm ",
        "Auteur/Editeur": "Imprimerie : Chez Goupil et Cie gravé par Ch Coppier"
    },
    {
        "﻿N°inventaire": "2 Fi 86",
        "Mode d'Acquisition": "M. Et Mme Paul Damour et Pellemelle Fonds 60 E",
        "Descriptif": "2 Fi 86  -  Certificat d’étude pour Louis Damour né le 8 février 1890 à Noirmoutier obtenu le 15 juin 1903",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "21 juillet 1903",
        "Lieu": "La Roche sur Yon ",
        "Descriptif/Technique": "papier",
        "Dimensions ": "35 x 27  cm",
        "Auteur/Editeur": "Imprimerie : Jourdais La Roche sur Yon "
    },
    {
        "﻿N°inventaire": "2 Fi  87 ",
        "Mode d'Acquisition": "Don Yvon Gauducheau. Fonds 152 E",
        "Descriptif": "2 Fi  87 – Portrait de marin de Constant Gauducheau 2ex",
        "Titre/Inscription": "Portrait",
        "Date d'Exécution": "",
        "Lieu": "Portrait sur le Gois Ile de Noirmoutier",
        "Descriptif/Technique": "papier- Reproduction d’un dessin coloré",
        "Dimensions ": "32 x 24 cm  ",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  88",
        "Mode d'Acquisition": "Don Yvon Gauducheau  Fonds 152 E",
        "Descriptif": "2 Fi  88 – Portrait d’une noirmoutrine en Quichenot ",
        "Titre/Inscription": "Portrait noirmoutrine en quichenotte ",
        "Date d'Exécution": "",
        "Lieu": "Portrait sur le Gois Ile de Noirmoutier",
        "Descriptif/Technique": "Papier- Reproduction d’un dessin coloré",
        "Dimensions ": "32 x24 x cm - (2 ex 22 x 16 cm)",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  89 ",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi  89  - Passage du Gois, balise ",
        "Titre/Inscription": "Paysage",
        "Date d'Exécution": "",
        "Lieu": "Ile de Noirmoutier Passage du Gois",
        "Descriptif/Technique": "papier- reproduction d’un dessin au crayon",
        "Dimensions ": "21 x 17 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  90 ",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi  90  - Le Château 5 ex",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "",
        "Lieu": "Noirmoutier ",
        "Descriptif/Technique": "Papier, reproductions de dessins au crayon",
        "Dimensions ": "19 x 14 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  91",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi  91 - Voiture de pompier devant le château 3 ex",
        "Titre/Inscription": "",
        "Date d'Exécution": "fin XIXe siècle",
        "Lieu": "Noirmoutier ",
        "Descriptif/Technique": "reproduction d’un dessin coloré (Nombreux exemplaires)",
        "Dimensions ": "24 x 17 cm  ",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  92",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi  92 – Passage du Gois avec une carriole tiré par un âne. 3 ex",
        "Titre/Inscription": "paysage",
        "Date d'Exécution": "XXe siècle",
        "Lieu": "Noirmoutier ",
        "Descriptif/Technique": "",
        "Dimensions ": "23 x 15 cm. Calendrier de sept oct 1987 30x24cm et mai juin 1993",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 93",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi 93 – Le pont de Noirmoutier 2 ex",
        "Titre/Inscription": "patrimoine",
        "Date d'Exécution": "Après 1969",
        "Lieu": "",
        "Descriptif/Technique": "Reproduction d’un dessin aquarellé",
        "Dimensions ": "24 x 16 cm  ",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  94",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi  94 - Balise du Gois et tour d’Arundel à La Chaume",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "Xxe siècle",
        "Lieu": "Noirmoutier et les Sables d’Olonne",
        "Descriptif/Technique": "reproduction de dessins au crayon",
        "Dimensions ": "21 x 29.7 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 95",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi 95 – Moulin de la Guérinière, Calvaire du Cheminet - Porte des Lions - La crypte Saint Philbert - 11 ex ",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "Xxe siècle",
        "Lieu": "",
        "Descriptif/Technique": "reproduction de dessins au crayon",
        "Dimensions ": "",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 96",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi  96 – La maison Tinguy à Noirmoutier (2ex)",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "Xxe siècle",
        "Lieu": "",
        "Descriptif/Technique": "Dessin couleur",
        "Dimensions ": "43 x 30 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  97",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": " 2 Fi 97 Château de Noirmoutier - Hotel Jacobsen et Le Breton des Grapières - La Blanche - L'Eglise Saint Philbert (10 ex)",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "",
        "Lieu": "",
        "Descriptif/Technique": "",
        "Dimensions ": "42 x 23 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi  98",
        "Mode d'Acquisition": "Don Yvon Gauducheau Fonds 152 E",
        "Descriptif": "2 Fi 98 la traversée du Gois par Charette et ses troupes",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "octobre 1793",
        "Lieu": "",
        "Descriptif/Technique": "papier- dessin coloré",
        "Dimensions ": "33 x 22 cm: ",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 FI 99",
        "Mode d'Acquisition": "Don  Mlle Biton. Combleux (Loiret)",
        "Descriptif": "2 Fi 99 Manuscrit rappelant un fait de Guerre du 13 Fructidor an 5 dont le héros fut Mathurin Musseau (encadré)",
        "Titre/Inscription": "Document historique",
        "Date d'Exécution": "5 Fructidor an 5",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Photographie encadrée",
        "Dimensions ": "",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 100",
        "Mode d'Acquisition": "Don Maurice Quenet Fonds 146 E",
        "Descriptif": "2 Fi 100 - Brevet de la marine marchande décerné à Jean Pineau pour son louable dévouement lors de la catrastrophe du Saint Philibert (encadré)",
        "Titre/Inscription": "Diplôme de la marine marchande",
        "Date d'Exécution": "07/11/1931",
        "Lieu": "Nantes",
        "Descriptif/Technique": "papier",
        "Dimensions ": "29 x 40 cm",
        "Auteur/Editeur": "Ministère de la marine"
    },
    {
        "﻿N°inventaire": "2 Fi 101",
        "Mode d'Acquisition": "Don Odette Percheron de La Madeleine soeur de Lucien Pontoizeau",
        "Descriptif": "2 Fi 101 – Certificat d’études primaires de Lucien Pontoizeau élève à l’école du Vieil ",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": "13 juin 1947",
        "Lieu": "Délivré par l’inspecteur d’Académie de Poitiers pour la Vendée",
        "Descriptif/Technique": "papier- Lithographie illustrée couleur",
        "Dimensions ": "52 x 41 cm",
        "Auteur/Editeur": "Imprimerie : Forveille  "
    },
    {
        "﻿N°inventaire": "2F 102",
        "Mode d'Acquisition": "Fonds Henri Martin  20 E",
        "Descriptif": "2 Fi 102 Diplôme de Peter Richer admis  comme membre du Grand Orient de France accompagné de sa médaille",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "2e mois de l'an de la vraie lumière 5807",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier reproduction N.B. illustrée",
        "Dimensions ": "57 x 53 cm",
        "Auteur/Editeur": "Merché Marchand F"
    },
    {
        "﻿N°inventaire": "2Fi 103",
        "Mode d'Acquisition": "Don Celestin Palvadeau Fonds 146 E",
        "Descriptif": "2 Fi 103 Médaille d'honneur de la marine marchande délivrée à Théodore Adrien, dessin de Marin Marie ",
        "Titre/Inscription": "Diplôme de la marine",
        "Date d'Exécution": "29 fevrier 1952",
        "Lieu": "Paris",
        "Descriptif/Technique": "Papier",
        "Dimensions ": "48 x 63",
        "Auteur/Editeur": "Ministère de la marine Marchande"
    },
    {
        "﻿N°inventaire": "2 Fi 104",
        "Mode d'Acquisition": "Don célestin Palvadeau Fonds 146 E",
        "Descriptif": "2 Fi 104 Certificat d'études primaires décerné à Jean Rabreau né à Soullans. Déssins d'André Curé instituteur à Barbâtre",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": " 12 juin 1954",
        "Lieu": "Ecole publique de Challans",
        "Descriptif/Technique": "papier repro couleur",
        "Dimensions ": "40 x 50 cm",
        "Auteur/Editeur": "imprimerie centrale de l'ouest   La Roche-sur- yon"
    },
    {
        "﻿N°inventaire": "2 Fi 105",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 105 - Affiche, \"Virgin dei Parae\"",
        "Titre/Inscription": "Affiche",
        "Date d'Exécution": "17 avril 1773",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier plastifié",
        "Dimensions ": "41 x 50 cm",
        "Auteur/Editeur": "Academiae. Typog. Viâ Franciscaâa"
    },
    {
        "﻿N°inventaire": "2 Fi 106",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 106 -Extrait du livret de la collection du Tour de France: \"Une capitale Française préhistorique\" par le Dr Baudouin",
        "Titre/Inscription": "Préhistoire",
        "Date d'Exécution": "1912",
        "Lieu": "grottes préhistoriques du sud-ouest de la France",
        "Descriptif/Technique": "papier. Lithographies ",
        "Dimensions ": "39 x 29 cm",
        "Auteur/Editeur": "Imprimé à Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 107",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 107 Publicitée faite pour la publication du livre \"Vendée-Militaire 1793-1796\" ",
        "Titre/Inscription": "Guerre de Vendée",
        "Date d'Exécution": "1793-1796",
        "Lieu": "Vendée Militaire",
        "Descriptif/Technique": "papier cartonné",
        "Dimensions ": "28 x 38 cm",
        "Auteur/Editeur": "Edition Pierre Gauthier"
    },
    {
        "﻿N°inventaire": "2 Fi 108",
        "Mode d'Acquisition": "Don Alain Jacobsen Fonds 45 E",
        "Descriptif": "Portrait de François Laurent Lamandé",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "1735-1718",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "reproduction photographique ",
        "Dimensions ": "27 x 36 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 109",
        "Mode d'Acquisition": "Don Hellio",
        "Descriptif": "2 Fi 109 Reprogravures du Bois de la Chaise plage des Dames d'après des cartes postales",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "Xxe siècle",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Papier cartonné",
        "Dimensions ": "60 x 23 cm",
        "Auteur/Editeur": "Ramuntcho, éditeur de cartes postales"
    },
    {
        "﻿N°inventaire": "2 Fi 110",
        "Mode d'Acquisition": "Don Hellio 149  E ",
        "Descriptif": "2 Fi 109 Reprogravures du Bois de la Chaise et la plage des Souzeaux",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "XXe sièle",
        "Lieu": "Noirmoutier - Le Pilier",
        "Descriptif/Technique": "Papier cartonné",
        "Dimensions ": "30 x 20",
        "Auteur/Editeur": "D'après des tableaux de Vincent-Darasse"
    },
    {
        "﻿N°inventaire": "2 F1 111",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 111  certificat d'Etudes primaires attribué à Auguste Guerin",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": "23 juin 1925",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "28 x 38 cm",
        "Auteur/Editeur": "Jean Foucher La Rochelle"
    },
    {
        "﻿N°inventaire": "2 Fi 112",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 112 Image de communion d'Auguste Guerin",
        "Titre/Inscription": "Diplôme Religieux",
        "Date d'Exécution": "29 janvier 1913",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Papier ",
        "Dimensions ": "30 x 46 cm",
        "Auteur/Editeur": "Bouasse Jeune Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 113",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 113 Etiquette illustrée d'identification de marin n° 42",
        "Titre/Inscription": "Marine",
        "Date d'Exécution": "",
        "Lieu": "",
        "Descriptif/Technique": "Papier",
        "Dimensions ": "20 x 20 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 114",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 114 Nouvelle imagerie d'Epinal. N° 16  Il pleut Bergère",
        "Titre/Inscription": "Image",
        "Date d'Exécution": "",
        "Lieu": "Epinal",
        "Descriptif/Technique": "papier",
        "Dimensions ": "28 x 40 cm",
        "Auteur/Editeur": "Lithographie Pinot et Sagaire Epinal"
    },
    {
        "﻿N°inventaire": "2 Fi 115",
        "Mode d'Acquisition": "Don Denis Guitton Fonds 150 E",
        "Descriptif": "2 Fi 115 - Journaux relatant la vie d'Harry Baur. 46 documents",
        "Titre/Inscription": "Presse",
        "Date d'Exécution": "1936-1937",
        "Lieu": "Paris",
        "Descriptif/Technique": "papier",
        "Dimensions ": "34 x 45 cm",
        "Auteur/Editeur": "Presse cinéphile"
    },
    {
        "﻿N°inventaire": "2 Fi 116",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 116 - Armée de terre et Armée de mer, ordre de mobilisation générale",
        "Titre/Inscription": "Affiche militaire",
        "Date d'Exécution": "2 août 1914",
        "Lieu": "Paris ",
        "Descriptif/Technique": "Papier encadré",
        "Dimensions ": "72 x 90 cm",
        "Auteur/Editeur": "Presse militaire"
    },
    {
        "﻿N°inventaire": "2 Fi 117",
        "Mode d'Acquisition": "Don Lemoing Fonds ",
        "Descriptif": "2 Fi 117 -\"Journée de la Vendée au profit des œuvres de guerre du comité départemental des secours pour les combattants,les blessés et les prisonniers de guerre de vendée\"",
        "Titre/Inscription": "Affiche militaire",
        "Date d'Exécution": "5 mars 1916",
        "Lieu": "Vendée ",
        "Descriptif/Technique": "Papier couleur illustré encadré",
        "Dimensions ": "80 x 116 cm ",
        "Auteur/Editeur": "Illustré par Poulbot"
    },
    {
        "﻿N°inventaire": "2 Fi 118",
        "Mode d'Acquisition": "Don Maurice Quenet Fonsds 55 E",
        "Descriptif": "2 Fi 118 Maquette de la Jonque chinoise Couang-Dzoui-Hann",
        "Titre/Inscription": "Marine",
        "Date d'Exécution": "",
        "Lieu": "",
        "Descriptif/Technique": "Papier",
        "Dimensions ": "110 x 78 cm",
        "Auteur/Editeur": "Marine Nationale"
    },
    {
        "﻿N°inventaire": "2 Fi 119",
        "Mode d'Acquisition": "Achat",
        "Descriptif": "couverture de revue édition Jacques Vautrin  monochrome rouge",
        "Titre/Inscription": "Document militaire",
        "Date d'Exécution": "",
        "Lieu": "",
        "Descriptif/Technique": "papier cartonné, illustration couleur",
        "Dimensions ": "28 x 38 cm",
        "Auteur/Editeur": "édition Jacques Vautrain"
    },
    {
        "﻿N°inventaire": "2 Fi 120",
        "Mode d'Acquisition": "Achat",
        "Descriptif": "2 Fi 120 - Brevet de capacité pour l'Enseignement Primaire  attribué à Jean Marie Charles Raimondeau",
        "Titre/Inscription": "Diplôme scolaire",
        "Date d'Exécution": "Décembre 1926",
        "Lieu": "Rennes",
        "Descriptif/Technique": "papier ",
        "Dimensions ": "40 x 27 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 121",
        "Mode d'Acquisition": "Don Sylvie soulard",
        "Descriptif": "2 Fi 121 - Carte des moulins dans l'Île de Noirmoutier",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "XIXe siècle",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "photocopie couleur",
        "Dimensions ": "30 x 42 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 122",
        "Mode d'Acquisition": "Don Alain Jacobsen Fonds 45 E",
        "Descriptif": "2Fi 122 - Portrait de Auguste Jacobsen enfant, photo d'un tableau",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "XVIIIe siècle",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Papier photo",
        "Dimensions ": "20 x 30 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 123",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 123 - Devenez propriétaire dans l'un des plus beau sites de France",
        "Titre/Inscription": "Affiche publicitaire",
        "Date d'Exécution": "XXIe siècle",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Papier monochrome",
        "Dimensions ": "40 x 60 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 124",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 124 - Médaille d'honneur en argent  attribué à Monsieur Boucard , conseiller municipal pour le courage et le dévouement dont il a fait preuve lors des inondations du Pulant",
        "Titre/Inscription": "Diplôme ",
        "Date d'Exécution": "Février 1838",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "37 x 46 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 125",
        "Mode d'Acquisition": "Dion",
        "Descriptif": "2 Fi 125 - Mission à l'Herbaudière en 1923   et  Mission à St Philbert  de Noirmoutier en Décembre 1919",
        "Titre/Inscription": "Affiche religieuse",
        "Date d'Exécution": "1919 et 1923",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "43 x 28 cm",
        "Auteur/Editeur": "Bayard Paris"
    },
    {
        "﻿N°inventaire": "2  Fi 126",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 126 - Souvenir Précieux à l'Âme Fidèle Anne Gendron",
        "Titre/Inscription": "diplôme Baptême et  confirmation communion ",
        "Date d'Exécution": "1886  - 1897",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "papier",
        "Dimensions ": "41 x 26 cm",
        "Auteur/Editeur": "Turgis Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 127",
        "Mode d'Acquisition": "Don",
        "Descriptif": "2 Fi 127 - Souvenir de la visite de l'escadre Russe  - Entrée de la Flotte Russe dans la rade de Toulon 1893",
        "Titre/Inscription": "Affiche militaire",
        "Date d'Exécution": "1893",
        "Lieu": "Toulon",
        "Descriptif/Technique": "Papier couleur illustré encadré",
        "Dimensions ": "56 x 70 cm",
        "Auteur/Editeur": "réalisée par Robert Jourdan. Imprimerie Becquet"
    },
    {
        "﻿N°inventaire": "2 Fi 128",
        "Mode d'Acquisition": "Gites minéraux",
        "Descriptif": "2 Fi 128  Etude des gites minéraux du bocage vendéen. 2 livres ",
        "Titre/Inscription": "Etude Géologique",
        "Date d'Exécution": "1854",
        "Lieu": "Vendée",
        "Descriptif/Technique": "papier",
        "Dimensions ": "56 x 37 cm",
        "Auteur/Editeur": "Imprimerie Royale Paris"
    },
    {
        "﻿N°inventaire": "2 Fi 129",
        "Mode d'Acquisition": "Achat Fonds Denis Guitton 81 E  ",
        "Descriptif": "2 Fi 129 Adolphe Boursin Permis de chasse 38 ans",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "18 aout 1875",
        "Lieu": "Plouermelmorbillan",
        "Descriptif/Technique": "papier ",
        "Dimensions ": "40 x 31",
        "Auteur/Editeur": " Ministère de l'interieur"
    },
    {
        "﻿N°inventaire": "2 Fi 130",
        "Mode d'Acquisition": "Diplôme  médaille commémorative guerre 1914-1918",
        "Descriptif": "Adolphe Boursin régiment de chasseurs d'afrique",
        "Titre/Inscription": "Diplôme",
        "Date d'Exécution": "Guerre 1914-1918",
        "Lieu": "La Marne",
        "Descriptif/Technique": "diplôme allégorique bicolor",
        "Dimensions ": "38x51",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 131   1 et 2",
        "Mode d'Acquisition": "Ancienne église de Saint Philibert de Granlieu étude et plan du révérend père de la Croix. 12 planches",
        "Descriptif": "photos et descriptif",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "fin XIXe",
        "Lieu": "Saint Philibert de Grand-Lieu",
        "Descriptif/Technique": "Photos de Jules Robuchon",
        "Dimensions ": "38 x 24",
        "Auteur/Editeur": "imprimerir Gillot"
    },
    {
        "﻿N°inventaire": "2 Fi 132",
        "Mode d'Acquisition": "Don",
        "Descriptif": "Brevet de Maître de Cabotage Jacques ADRIEN",
        "Titre/Inscription": "Diplôme de la marine",
        "Date d'Exécution": "08-mars-05",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Papier Velin",
        "Dimensions ": "24 x 37 cm",
        "Auteur/Editeur": "Administration centrale de la marine"
    },
    {
        "﻿N°inventaire": "2 Fi 133",
        "Mode d'Acquisition": "Don",
        "Descriptif": " 17 reproductions de cartes postales de Fromentine ",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "Xxe siècle",
        "Lieu": "Fromentine",
        "Descriptif/Technique": "Papier",
        "Dimensions ": "42 cm x 28 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 134",
        "Mode d'Acquisition": "Don Odile de Jame et Jean Philippe L'houtellier",
        "Descriptif": "Typographie dune aquarelle représentant la ville de Noirmoutier et ses marais",
        "Titre/Inscription": "Patrimoine",
        "Date d'Exécution": "1979",
        "Lieu": "Noirmoutier",
        "Descriptif/Technique": "Rodoïde",
        "Dimensions ": "37 x 24 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2  Fi 135",
        "Mode d'Acquisition": "Fonds  96 E",
        "Descriptif": "Catrastrophe du Saint Philibert",
        "Titre/Inscription": "Presse, Montréal",
        "Date d'Exécution": "15 juin 1931",
        "Lieu": "Baie de Bourgneuf",
        "Descriptif/Technique": "Article sur la catastrophe",
        "Dimensions ": "60 x 43 cm",
        "Auteur/Editeur": "Journal La Patrie, Montréal"
    },
    {
        "﻿N°inventaire": "2 Fi 136",
        "Mode d'Acquisition": "",
        "Descriptif": "16 Photographies de Jules Robuchon",
        "Titre/Inscription": "",
        "Date d'Exécution": "",
        "Lieu": "Ile de Noirmoutier Ile d'yeu",
        "Descriptif/Technique": "",
        "Dimensions ": "18 x 13 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 137",
        "Mode d'Acquisition": "Don  Brelaudier ",
        "Descriptif": "Fleur de misère. Le patron est Gustave Gendron, à la barre de son bâteau",
        "Titre/Inscription": "",
        "Date d'Exécution": "2/ 96",
        "Lieu": "",
        "Descriptif/Technique": "",
        "Dimensions ": "",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 138",
        "Mode d'Acquisition": "Achat",
        "Descriptif": "publicité Maison Frioux Barbatre",
        "Titre/Inscription": "Quincallerie",
        "Date d'Exécution": "h 49, 21,5",
        "Lieu": "Papier gaufré colorisé",
        "Descriptif/Technique": "",
        "Dimensions ": "",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 139",
        "Mode d'Acquisition": "",
        "Descriptif": "7 Dessins à l'encre de chine aquarellés",
        "Titre/Inscription": "Scènes de rue",
        "Date d'Exécution": "1947",
        "Lieu": "Papier dessins à l'encre de chine aquarellé",
        "Descriptif/Technique": "",
        "Dimensions ": "34 x 25 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 140",
        "Mode d'Acquisition": "",
        "Descriptif": "7 Dessins asiatiques provenant du cambodge et du Vietnam",
        "Titre/Inscription": "Scènes de rue",
        "Date d'Exécution": "1947",
        "Lieu": "Papier. Encre de chine aquarellée",
        "Descriptif/Technique": "",
        "Dimensions ": "32 x 50 cm",
        "Auteur/Editeur": ""
    },
    {
        "﻿N°inventaire": "2 Fi 141",
        "Mode d'Acquisition": "",
        "Descriptif": "Georges Scott:Reproduction d'aquarelle representant lechamps de bataille guerre 1914-1918",
        "Titre/Inscription": "Guerre 1914-1918",
        "Date d'Exécution": "",
        "Lieu": "Papier. Reproduction d'aquarelle",
        "Descriptif/Technique": "",
        "Dimensions ": "62 x 40 cm",
        "Auteur/Editeur": ""
    }
];