var ArcDatabase = [
    {
        "﻿Référence": "4 Fi 10",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Clair de lune – reflets sur la mer  référencé  E-36",
        "Inscription": "",
        "Objet": "voilier et reflets de lune",
        "Date": "1924",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "19 x 29 cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 100",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Les marais de Noirmoutier",
        "Inscription": "Non signé",
        "Objet": "Marais salants",
        "Date": "1e moitié du XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Gouache",
        "Support": "Papier",
        "Dimensions": "47,5 x 41 cm",
        "Modalités d'entrée": "Don Jean Vincent - Darasse",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 – 25"
    },
    {
        "﻿Référence": "4 Fi 101",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Les marais de Noirmoutier",
        "Inscription": "J. Vincent - Darasse",
        "Objet": "Marais salants",
        "Date": "1e moitié du XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Gouache",
        "Support": "Papier",
        "Dimensions": "47,5 x 41 cm",
        "Modalités d'entrée": "Don Jean Vincent - Darasse  octobre 1980",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 – 26"
    },
    {
        "﻿Référence": "4 Fi 102",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Les marais salants de Noirmoutier",
        "Inscription": "J. Vincent - Darasse",
        "Objet": "Mulon devant le château et l’église",
        "Date": "1e moitié du XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Gouache",
        "Support": "Papier",
        "Dimensions": "47,5 x 41 cm",
        "Modalités d'entrée": "Don Jean Vincent - Darasse 1980",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 – 27"
    },
    {
        "﻿Référence": "4 Fi 103",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Noirmoutier",
        "Inscription": "J. Vincent - Darasse",
        "Objet": "Paysage",
        "Date": "1e moitié du XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Gouache",
        "Support": "Papier",
        "Dimensions": "47,5 x 41 cm",
        "Modalités d'entrée": "Don Jean Vincent-Darasse  octobre 1980",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 - 28"
    },
    {
        "﻿Référence": "4 Fi 104",
        "Auteur": "Marie Vincent-Darasse ?",
        "Titre": "Paysage de bord de mer",
        "Inscription": "Ma [illisible]",
        "Objet": "Paysage",
        "Date": "Vers 1900",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "Toile sans châssis",
        "Dimensions": "27 x 23,5 cm",
        "Modalités d'entrée": "Don Clément Corbrejaud",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 995 - 5"
    },
    {
        "﻿Référence": "4 Fi 105",
        "Auteur": "Aurait été peint par Jean Vincent-Darasse",
        "Titre": "Paysage de bord de mer",
        "Inscription": "Sans",
        "Objet": "Paysage",
        "Date": "avant 1955",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "huile sur bois",
        "Support": "Bois",
        "Dimensions": "33 x 19 cm",
        "Modalités d'entrée": "don Clément Corbrejaud",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 995 - 6"
    },
    {
        "﻿Référence": "4 Fi 106",
        "Auteur": "Gilbert Bellan",
        "Titre": "Chemin sous les arbres",
        "Inscription": "",
        "Objet": "Allée forestière",
        "Date": "1er moitié du XIXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "76 x 97 cm",
        "Modalités d'entrée": "Don  Mme Huchery 1951",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 21b"
    },
    {
        "﻿Référence": "4 Fi 107",
        "Auteur": "Gilbert Bellan",
        "Titre": "La ferme des coques",
        "Inscription": "Gilbert Bellan",
        "Objet": "Ferme traditionnelle",
        "Date": "1er moitié du XIXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "78 x 98 cm",
        "Modalités d'entrée": "Don de Mme Huchery  1955",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 23"
    },
    {
        "﻿Référence": "4 Fi 108",
        "Auteur": "Gilbert Bellan",
        "Titre": "Paysage Boisé",
        "Inscription": "Gilbert Bellan",
        "Objet": "Paysage",
        "Date": "1er moitié du XIXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "96 x 76 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 24"
    },
    {
        "﻿Référence": "4 Fi 109",
        "Auteur": "Gilbert Bellan",
        "Titre": "Le moulin de la loire",
        "Inscription": "",
        "Objet": "Paysage",
        "Date": "XIXe siècle",
        "Lieu": "La Guérinière, Île de Noirmoutier",
        "Technique": "Huile",
        "Support": "Papier",
        "Dimensions": "96 x 76 cm",
        "Modalités d'entrée": "En dépôt  au Musée de La Guérinière",
        "Note": "Inscrit à l’inventaire"
    },
    {
        "﻿Référence": "4 Fi 11",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Bateau au soleil couchant. Référencé  E-25",
        "Inscription": "",
        "Objet": "Bateau au soleil couchant",
        "Date": "1923",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "18,5 x 26   cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 110",
        "Auteur": "Théodore de Kolly",
        "Titre": "Vue d’un chargement de sel sur le brick « Les deux Amis », près de l’étier de l’Arceau",
        "Inscription": "",
        "Objet": "Chargement du sel",
        "Date": "Avant 1828",
        "Lieu": "Noirmoutier en l’île",
        "Technique": "Gouache, aquarelle et encre",
        "Support": "Papier",
        "Dimensions": "x cm",
        "Modalités d'entrée": "Achat à Mme Henri Martin",
        "Note": "Ce tableau est en dépôt au Musée de La Guérinière"
    },
    {
        "﻿Référence": "4 Fi 111",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Paysage",
        "Inscription": "F. Palvadeau",
        "Objet": "Paysage",
        "Date": "2e moitié du XIXe",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "95 x 64 cm",
        "Modalités d'entrée": "Don 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 39"
    },
    {
        "﻿Référence": "4 Fi 112",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Femme lisant sous les arbres",
        "Inscription": "",
        "Objet": "Paysage",
        "Date": "2e moitié du XIXe siècle",
        "Lieu": "France",
        "Technique": "Huile sur carton",
        "Support": "Carton",
        "Dimensions": "56 x 64 cm",
        "Modalités d'entrée": "Achat à Mme Anne Mathieu (Palvadeau) 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 370"
    },
    {
        "﻿Référence": "4 Fi 113",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Paysage",
        "Inscription": "F. Palvadeau",
        "Objet": "Paysage",
        "Date": "2e moitié du XIXe",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Carton bouilli",
        "Dimensions": "34 x 50,5 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 371"
    },
    {
        "﻿Référence": "4 Fi 114",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Phare, plage, bateau, 7 personnages",
        "Inscription": "F. Palvadeau",
        "Objet": "Marine",
        "Date": "2e moitié du XIXe",
        "Lieu": "France",
        "Technique": "Huile sur toile",
        "Support": "Toile",
        "Dimensions": "56 x 43 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 372"
    },
    {
        "﻿Référence": "4 Fi 115",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Paysage automnal",
        "Inscription": "F. Palvadeau",
        "Objet": "Paysage",
        "Date": "2e moitié du XIXe",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "49,5 x 42,5 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 373"
    },
    {
        "﻿Référence": "4 Fi 116",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Vue de la mer, phare et un personnage",
        "Inscription": "F. Palvadeau",
        "Objet": "Marine",
        "Date": "2e moitié du XIXe",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "38,5 x 26 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 374"
    },
    {
        "﻿Référence": "4 Fi 117",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Aspect du Bois de la Chaise",
        "Inscription": "",
        "Objet": "Paysage",
        "Date": "XXe siècle",
        "Lieu": "Île de Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton bouilli",
        "Dimensions": "22 x 33 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 375"
    },
    {
        "﻿Référence": "4 Fi 118",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Bord de la Boulogne",
        "Inscription": "",
        "Objet": "Paysage",
        "Date": "2e moitié du XIXe siècle",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "35 x 47,5 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 376"
    },
    {
        "﻿Référence": "4 Fi 119",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Marée basse à Noirmoutier",
        "Inscription": "Au dos, Ile de Noirmoutier 1860 à marée basse",
        "Objet": "Marine",
        "Date": "1860",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton bouilli",
        "Dimensions": "39 x 28 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 377"
    },
    {
        "﻿Référence": "4 Fi 12",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Femme à la coiffe de l’île d’Yeu. Référencé  A-39",
        "Inscription": "",
        "Objet": "Portrait",
        "Date": "1927",
        "Lieu": "Ile d’Yeu",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "35 x 26,5   cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 120",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Allée de forêt en été",
        "Inscription": "F. Palvadeau",
        "Objet": "Paysage",
        "Date": "2e moitié du XIXe siècle",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Carton bouilli",
        "Dimensions": "16,5 x 20 cm",
        "Modalités d'entrée": "Achat 1949",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 379"
    },
    {
        "﻿Référence": "4 Fi 121",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Le port de Saint-Nazaire ?",
        "Inscription": "",
        "Objet": "Marine",
        "Date": "XIXe siècle",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Carton bouilli",
        "Dimensions": "52 x 40 cm",
        "Modalités d'entrée": "Florimond Palvadeau",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 380"
    },
    {
        "﻿Référence": "4 Fi 122",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Un grain à Noirmoutier",
        "Inscription": "F. Palvadeau",
        "Objet": "Marine",
        "Date": "1880",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "30,5 x 43,5 cm",
        "Modalités d'entrée": "Don 1949 ?",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 381"
    },
    {
        "﻿Référence": "4 Fi 123",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Retour à la chaumière le soir",
        "Inscription": "Au dos, Muller Paris",
        "Objet": "Paysage animé",
        "Date": "2e moitié du XIXe siècle",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Carton bouilli",
        "Dimensions": "27 x 35,5 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984-382"
    },
    {
        "﻿Référence": "4 Fi 125",
        "Auteur": "",
        "Titre": "Deux jeunes femmes",
        "Inscription": "",
        "Objet": "Portrait",
        "Date": "Début XXe siècle",
        "Lieu": "France",
        "Technique": "Pastel",
        "Support": "toile",
        "Dimensions": "21,5 x 26.7 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 -51"
    },
    {
        "﻿Référence": "4 Fi 126",
        "Auteur": "Maurice Orange",
        "Titre": "Portait d’un chef de musique dans l’armée napoléonienne",
        "Inscription": "",
        "Objet": "Militaire",
        "Date": "1900",
        "Lieu": "France",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "55 x 75 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 28"
    },
    {
        "﻿Référence": "4 Fi 127",
        "Auteur": "M. Mathieu",
        "Titre": "Vue de Noirmoutier",
        "Inscription": "Au dos : M. Mathieu",
        "Objet": "paysage",
        "Date": "XXe siècle",
        "Lieu": "Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "31,5 x 23,8 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 253"
    },
    {
        "﻿Référence": "4 Fi 128",
        "Auteur": "Gilles Lorber",
        "Titre": "Lorber : Carénage",
        "Inscription": "Carénage.  Lorber",
        "Objet": "Bateaux",
        "Date": "",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Papier",
        "Dimensions": "40 x 60 cm",
        "Modalités d'entrée": "Don M. Filluzeau",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 988 -"
    },
    {
        "﻿Référence": "4 Fi 129",
        "Auteur": "E. Arnaud",
        "Titre": "Ferme de la Belle -Vue",
        "Inscription": "E. Arnaud",
        "Objet": "Paysage",
        "Date": "Début XXe siècle",
        "Lieu": "Île de Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "49 x 39 cm",
        "Modalités d'entrée": "Don Amis des Musées",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 990 – 31"
    },
    {
        "﻿Référence": "4 Fi 13",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Rochers en bord de mer avec personnages. Référencé C-47",
        "Inscription": "",
        "Objet": "Femme et enfant sur un rocher regardant des voiliers",
        "Date": "1920",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "28 x 35  cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 130",
        "Auteur": "Anonyme probablement noirmoutrin qui a exécuté cette peinture pour un devant de cheminée",
        "Titre": "Scène de combat naval",
        "Inscription": "",
        "Objet": "Combat naval entre Français et Anglais",
        "Date": "Fin XVIIIe siècle",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 -"
    },
    {
        "﻿Référence": "4 Fi 131",
        "Auteur": "W.F.",
        "Titre": "Portrait de Pierre L’Ermite",
        "Inscription": "",
        "Objet": "Portrait",
        "Date": "",
        "Lieu": "France",
        "Technique": "Pastel",
        "Support": "Papier",
        "Dimensions": "32,5 x 43 cm",
        "Modalités d'entrée": "Donné à Mr l’abbé Bordereau en 1930",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 995 - 8"
    },
    {
        "﻿Référence": "4 Fi 132",
        "Auteur": "",
        "Titre": "Portrait de François Piet",
        "Inscription": "",
        "Objet": "Portrait",
        "Date": "XXe siècle",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "69 x 92 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 25"
    },
    {
        "﻿Référence": "4 Fi 133",
        "Auteur": "",
        "Titre": "Vue de l’Epine (Noirmoutier)",
        "Inscription": "",
        "Objet": "Paysage",
        "Date": "Début XIXe siècle",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Lavis",
        "Support": "Papier",
        "Dimensions": "36,5 x 25 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 120"
    },
    {
        "﻿Référence": "4 Fi 134",
        "Auteur": "Auguste Berthomé",
        "Titre": "Le naufrage de La Jeanne",
        "Inscription": "",
        "Objet": "Le navire est sur le point d’être abordé",
        "Date": "",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "",
        "Modalités d'entrée": "Donné en 1991 par Mme Jeanne Gautier-Bouteau descendante d’Auguste Berthomé (Fonds 67 E). En dépôt au Musée de la Guérinière",
        "Note": "Inscrit à l’inventaire du Musée sous le numéro"
    },
    {
        "﻿Référence": "4 Fi 135",
        "Auteur": "",
        "Titre": "L’adoration des mages",
        "Inscription": "",
        "Objet": "",
        "Date": "",
        "Lieu": "France",
        "Technique": "",
        "Support": "",
        "Dimensions": "",
        "Modalités d'entrée": "",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 14",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Maisons en bord de mer avec arbre. Référencé E-64",
        "Inscription": "",
        "Objet": "paysage",
        "Date": "1926",
        "Lieu": "Ile d’Yeu",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "26 x 37  cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 15",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Bateaux à Noirmoutier avec vapeur. Référencé  E-20",
        "Inscription": "",
        "Objet": "voilier et vapeur",
        "Date": "1923",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "26 x 39,5  cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 16",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Tempête sur l’océan à Noirmoutier. Référencé E-24",
        "Inscription": "",
        "Objet": "Tempête et bateau",
        "Date": "1923",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "24 x 32,5  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 17",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Bord de mer à Noirmoutier. Référencé  E-30",
        "Inscription": "",
        "Objet": "bord de mer",
        "Date": "1923",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "24 x 33,5  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 18",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "L’anse Rouge. Référencé E-38",
        "Inscription": "",
        "Objet": "Anse Rouge et tour Plantier",
        "Date": "1924",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "46 x 55,5  cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 19",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Bateaux à Noirmoutier. Référencé E-42",
        "Inscription": "",
        "Objet": "Voiliers",
        "Date": "1925",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "35 x 27   cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 2",
        "Auteur": "Henri Lefort",
        "Titre": "Plage du Bois de la Chaise",
        "Inscription": "Henri Lefort",
        "Objet": "Paysage",
        "Date": "",
        "Lieu": "Ile de Noirmoutier (plage des Dames ?)",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "15 x 20 cm",
        "Modalités d'entrée": "Achat 2014",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 20",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Régates à Noirmoutier. Référencé E 27",
        "Inscription": "",
        "Objet": "Voiliers  lors d’une régate au bois de la chaise",
        "Date": "1923",
        "Lieu": "Noirmoutier",
        "Technique": "Pastel",
        "Support": "Carton",
        "Dimensions": "38 x 47   cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 21",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Pointe Saint Pierre. Référencé E-43",
        "Inscription": "",
        "Objet": "Rochers",
        "Date": "1925",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "27 x 36,5  cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 22",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Retour de pêche au coucher du soleil. Référencé E-29",
        "Inscription": "",
        "Objet": "Bateau de pêche",
        "Date": "1923",
        "Lieu": "Noirmoutier",
        "Technique": "Pastel",
        "Support": "Bois",
        "Dimensions": "24 x 32,5  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 23",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Plage des Dames. Référencé  E 23",
        "Inscription": "",
        "Objet": "Trois personnages se baignant devant une barque et des voiliers",
        "Date": "1923",
        "Lieu": "Ile de Noirmoutier, plage des Dames pointe Saint Pierre",
        "Technique": "Pastel",
        "Support": "Bois",
        "Dimensions": "25 x 35  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 24",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Enfant au petit bateau. Référencé  C 49",
        "Inscription": "",
        "Objet": "Enfant à la plage",
        "Date": "1925",
        "Lieu": "Noirmoutier",
        "Technique": "Pastel",
        "Support": "Bois",
        "Dimensions": "27 x 35  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 25",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Bateaux à Noirmoutier. Référencé E-32",
        "Inscription": "",
        "Objet": "Deux bateaux",
        "Date": "1923",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "24 x 33 cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 26",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Lever du soleil sur l’océan. Référencé  E-35",
        "Inscription": "",
        "Objet": "Lever sur soleil sur l’océan",
        "Date": "1924",
        "Lieu": "Noirmoutier",
        "Technique": "Pastel",
        "Support": "carton",
        "Dimensions": "24,5 x 33,5  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 27",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Arrivée de bateaux. Référencé E-6",
        "Inscription": "",
        "Objet": "Deux bateaux, l’un à voile l’autre à vapeur",
        "Date": "1920",
        "Lieu": "Noirmoutier",
        "Technique": "Pastel",
        "Support": "carton",
        "Dimensions": "25 x 33,5  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 28",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Coucher du soleil. Référencé E-21",
        "Inscription": "",
        "Objet": "Coucher du soleil sur la mer",
        "Date": "1923",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Pastel",
        "Support": "carton",
        "Dimensions": "24 x 32,5  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 29",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Coucher du soleil sur l’océan. Référencé E-22",
        "Inscription": "",
        "Objet": "Coucher du soleil sur la mer",
        "Date": "1923",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Pastel",
        "Support": "carton",
        "Dimensions": "24 x 33  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 3",
        "Auteur": "Grenko",
        "Titre": "Grenko : Port de pêche de l’Herbaudière",
        "Inscription": "L’aventure sardinière  à  L’Herbaudière – 1880-1967",
        "Objet": "Maquette réalisée pour la couverture du N° 5 de la collection « Noirmoutier à travers l’Histoire » publié par l’AAIN (2 ex)",
        "Date": "2010",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Papier Canson",
        "Dimensions": "33 x 50 cm",
        "Modalités d'entrée": "Don du peintre Mme Launeau dit Grenko",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 30",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Retour de pêche au coucher du soleil. Référencé E-28",
        "Inscription": "",
        "Objet": "Bateaux sous voile au coucher du soleil",
        "Date": "1923",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Pastel",
        "Support": "carton",
        "Dimensions": "30 x 40  cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 31",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Port de l’Herbaudière. Référencé E-19",
        "Inscription": "",
        "Objet": "Bateaux sous voile au coucher du soleil",
        "Date": "1923",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Pastel",
        "Support": "carton",
        "Dimensions": "30 x 40  cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 32",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Rocher. Référencé E 33",
        "Inscription": "",
        "Objet": "Rocher en pointe sur la mer",
        "Date": "1923-1925",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "24 x 33 cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 33",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Retour de pêche à L’île de Noirmoutier. Référencé C-55",
        "Inscription": "",
        "Objet": "Marins déchargeant un bateau dans le port de l’Herbaudière",
        "Date": "1925-1926",
        "Lieu": "Port de l’Herbaudière",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "38,5 x 55 cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 34",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Port de l’Herbaudière. Référencé E-13",
        "Inscription": "",
        "Objet": "Voiliers",
        "Date": "1922",
        "Lieu": "l’Herbaudière, ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "26,5 x 36,5 cm",
        "Modalités d'entrée": "Don Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 35",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Ile de Noirmoutier Bateaux – Enfants Référencé C-48",
        "Inscription": "",
        "Objet": "Voiliers et barque avec des enfants",
        "Date": "1923",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "pastel",
        "Support": "Carton",
        "Dimensions": "27 x 36,5 cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 35 bis",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Ile de Noirmoutier Bateaux – Les régates à Noirmoutier. Non référencé ?",
        "Inscription": "",
        "Objet": "Régates",
        "Date": "1922",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "pastel",
        "Support": "Carton",
        "Dimensions": "33 x 25 cm",
        "Modalités d'entrée": "Don  Jacques Noireau",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 36",
        "Auteur": "L. Humbert",
        "Titre": "L’église et le nouveau presbytère",
        "Inscription": "L. Humbert",
        "Objet": "Eglise de St Philbert",
        "Date": "vers 1920",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "",
        "Modalités d'entrée": "Don André Commard 1994",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 37",
        "Auteur": "L. Humbert",
        "Titre": "Le Donjon et l’église St Philbert vue du marais de Goisy",
        "Inscription": "L. Humbert",
        "Objet": "patrimoine architectural",
        "Date": "XIXe",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Carton toilé",
        "Dimensions": "26 x 36",
        "Modalités d'entrée": "Don Jean Laidin  1986",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 38",
        "Auteur": "Yvon Dieulafé",
        "Titre": "Bourrine Marais Vendéen",
        "Inscription": "Yvon Dieulafé",
        "Objet": "Habitation traditionnelle vendéenne",
        "Date": "Vers 1990",
        "Lieu": "Vendée",
        "Technique": "Huile",
        "Support": "Isorel",
        "Dimensions": "35 x 24 cm",
        "Modalités d'entrée": "Don Bernard Chupin",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 39",
        "Auteur": "Yvon Dieulafé",
        "Titre": "L’Estacade du Bois de la Chaise la nuit",
        "Inscription": "Yvon Dieulafé",
        "Objet": "Paysage",
        "Date": "Vers 1990",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Isorel",
        "Dimensions": "35 x 24 cm",
        "Modalités d'entrée": "Achat 1998",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 4",
        "Auteur": "Métivier",
        "Titre": "Deux moulins de La Guérinière",
        "Inscription": "Métivier",
        "Objet": "Architecture traditionnelle",
        "Date": "1952",
        "Lieu": "la Guérinière, ile de Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "carton",
        "Dimensions": "33 x 30 cm",
        "Modalités d'entrée": "",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 40",
        "Auteur": "Yvon Dieulafé",
        "Titre": "Plage de Vendée",
        "Inscription": "",
        "Objet": "Paysage",
        "Date": "Vers 1990",
        "Lieu": "Vendée",
        "Technique": "Huile",
        "Support": "Isorel",
        "Dimensions": "46 x 38 cm",
        "Modalités d'entrée": "Don Bernard Chupin",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 41",
        "Auteur": "Yvon Dieulafé",
        "Titre": "Plage de de l’Anse Rouge et Tour Plantier",
        "Inscription": "Yvon Dieulafé",
        "Objet": "Paysage",
        "Date": "Vers 1990",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Isorel encadré",
        "Dimensions": "60 x 45 cm",
        "Modalités d'entrée": "Don Bernard Chupin",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 42",
        "Auteur": "Ambroise Baudry",
        "Titre": "Noirmoutier",
        "Inscription": "",
        "Objet": "Intérieur d’église (les personnages sont identifiés)",
        "Date": "7 octobre 1889",
        "Lieu": "Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "84 x 65 cm",
        "Modalités d'entrée": "Don Gilles Rhoné - 2016",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 43",
        "Auteur": "J. Raoup",
        "Titre": "Vue de la maison « La Guilletière »",
        "Inscription": "Souvenir de bonnes vacances",
        "Objet": "Architecture",
        "Date": "1933",
        "Lieu": "l’Epine, Ile de  Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Papier Canson",
        "Dimensions": "33,5 x 23,5 cm",
        "Modalités d'entrée": "Christophe Corbrejaud de l’Epine",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 44",
        "Auteur": "Claude Evein",
        "Titre": "Vue d’une rue de Noirmoutier près du Château",
        "Inscription": "Marqué sur une étiquette au dos du tableau : Rue du Moulin Raimbault N° 013 1944",
        "Objet": "Paysage",
        "Date": "1944",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Isorel",
        "Dimensions": "27 x 23 cm (3 F)",
        "Modalités d'entrée": "Achat 1983 ?",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 45",
        "Auteur": "",
        "Titre": "Portrait d’Arsène Charier-Fillon",
        "Inscription": "",
        "Objet": "Portrait",
        "Date": "vers 1870",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "73 x 59,50 cm",
        "Modalités d'entrée": "Achat   (Fonds 156 E)",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 46",
        "Auteur": "E.T.",
        "Titre": "Portrait d’un gentilhomme romantique dans  un cadre ancien doré",
        "Inscription": "E.T",
        "Objet": "Portrait en pied",
        "Date": "XIXe siècle",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "27 x 21.5 cm",
        "Modalités d'entrée": "Don Charley Garet 2014 (Fonds 9 E)",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 47",
        "Auteur": "Ripper",
        "Titre": "Ciel Romancé",
        "Inscription": "Ripper. Ciel Romancé",
        "Objet": "Marine",
        "Date": "2001",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Toile encadrée",
        "Dimensions": "61 x 49 cm",
        "Modalités d'entrée": "France Bergeron  alias Ripper",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 48",
        "Auteur": "Ripper",
        "Titre": "Ciel dévoreur",
        "Inscription": "Ciel dévoreur",
        "Objet": "Marine",
        "Date": "",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Toile encadrée",
        "Dimensions": "62 x 48 cm",
        "Modalités d'entrée": "France Bergeron alias Ripper",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 49",
        "Auteur": "ANNZ",
        "Titre": "Passage du Gois au clair de lune",
        "Inscription": "ANNZ",
        "Objet": "Marine",
        "Date": "",
        "Lieu": "Le Gois, Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile encadrée",
        "Dimensions": "",
        "Modalités d'entrée": "inconnue",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 5",
        "Auteur": "Joyce Béranger",
        "Titre": "Les Moulins de la Cour à la Guérinière",
        "Inscription": "",
        "Objet": "Architecture traditionnelle",
        "Date": "1985",
        "Lieu": "La Guérinière, Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "toile cartonnée",
        "Dimensions": "61 x 50 cm",
        "Modalités d'entrée": "Don Joyce Béranger",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 50",
        "Auteur": "Sophie Rousseau",
        "Titre": "Plage des dames à l’aube",
        "Inscription": "",
        "Objet": "Cabines de bain plage des dames",
        "Date": "1984",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "20 x 14 cm",
        "Modalités d'entrée": "Achat juillet 1985",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 51",
        "Auteur": "Jean-Jacques Trichet",
        "Titre": "Marée basse au port de l’Herbaudière Noirmoutier",
        "Inscription": "J.J Trichet",
        "Objet": "Marine",
        "Date": "22/08/2018",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "46 x 55 cm",
        "Modalités d'entrée": "Don Jean-Jacques Trichet",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 52",
        "Auteur": "",
        "Titre": "Composition imaginaire sur Noirmoutier",
        "Inscription": "Noirmoutier",
        "Objet": "Différents lieux de Noirmoutier",
        "Date": "",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Tranche ovale de sapin",
        "Dimensions": "40 x 13 cm",
        "Modalités d'entrée": "Don Jean Laidin 1987",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 53",
        "Auteur": "",
        "Titre": "Ecu représentant les armoiries de la famille Jacobsen",
        "Inscription": "Wyselick – Vromelyck",
        "Objet": "Devise de la famille Jacobsen",
        "Date": "1787",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Panneau de bois",
        "Dimensions": "",
        "Modalités d'entrée": "Don Mme Huyghebaert 2010 (Fonds 21 E    )",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 54",
        "Auteur": "Pierre Courtois",
        "Titre": "Pierre Courtois, peintre de la marine : Port de Noirmoutier en l’île",
        "Inscription": "Courtois",
        "Objet": "Marine",
        "Date": "",
        "Lieu": "île de Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "65 x 50 cm",
        "Modalités d'entrée": "Don du peintre Pierre Courtois",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 55",
        "Auteur": "",
        "Titre": "Portrait de Mathieu Alexandre Plantier ( ?-1750)",
        "Inscription": "Le nom de Plantier apparait en bas à droite du tableau mais semble postérieur au portrait",
        "Objet": "Mathieu Alexandre Plantier avocat au parlement, receveur général du duché de Retz. (Lettre aux Amis n° 164)",
        "Date": "XVIIIe siècle",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "92 x 73 cm",
        "Modalités d'entrée": "Dépôt des descendants du propriétaire du tableau",
        "Note": "L’œuvre est rentoilée, présenté dans un cadre en bois stuqué décoré de feuille, postérieur à l’œuvre"
    },
    {
        "﻿Référence": "4 Fi 56",
        "Auteur": "Bachelet",
        "Titre": "Bateaux en rade du Bois de la Chaise",
        "Inscription": "",
        "Objet": "Marine",
        "Date": "1793",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois de Balsa (manque un angle)",
        "Dimensions": "18.3 x 13 cm",
        "Modalités d'entrée": "Achat 1994",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 57",
        "Auteur": "",
        "Titre": "Portrait de Commard de Puylorson",
        "Inscription": "messire André Commard de Puylorsson né en  Noirmoutier en 1710 prêtre docteur en théologie chanoine de l’eglise royale de guérande en 1746",
        "Objet": "portrait en buste",
        "Date": "fin XVIIIe sicle",
        "Lieu": "",
        "Technique": "Gouache et encre",
        "Support": "papier contrecollé sur carton",
        "Dimensions": "16 x 10 cm",
        "Modalités d'entrée": "inconnue",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 58",
        "Auteur": "",
        "Titre": "Tablier de Franc-maçon évoquant la légende de Zorobabel prince juif et de Cyrus roi de Babylone",
        "Inscription": "",
        "Objet": "Symboles maçonniques",
        "Date": "modèle datant du XVIIIe siècle",
        "Lieu": "",
        "Technique": "Lithographie rehaussée d’aquarelle",
        "Support": "Peau de mouton",
        "Dimensions": "28 x 29 cm",
        "Modalités d'entrée": "Ce tablier de Franc-maçon  a été trouvé dans le grenier d’une maison rue du Général Passaga et acheté en 2007",
        "Note": "Marqué : A Paris chez Guérin, Palais du Travail"
    },
    {
        "﻿Référence": "4 Fi 59",
        "Auteur": "Charles Bugeon dit Charles X",
        "Titre": "Trois mâts",
        "Inscription": "Charles X B",
        "Objet": "Bateau à voiles",
        "Date": "",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "43 x 29 cm",
        "Modalités d'entrée": "Don Mme  J. Pennec 1999",
        "Note": "(non référencé)"
    },
    {
        "﻿Référence": "4 Fi 6",
        "Auteur": "Hélène de Lajallet",
        "Titre": "Paysage de bord de mer",
        "Inscription": "Lajallet",
        "Objet": "La pointe Saint Pierre au Bois de la Chaise",
        "Date": "XXe siècle",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile présentée dans un cadre doré ancien",
        "Dimensions": "27 x 46 cm",
        "Modalités d'entrée": "Achat  Paris, Etude Beaussan Lefèvre. Octobre 2016",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 60",
        "Auteur": "Charles Bugeon dit Charles X",
        "Titre": "Deux mâts",
        "Inscription": "Charles X B",
        "Objet": "Bateau à voiles",
        "Date": "",
        "Lieu": "",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "43 x 29",
        "Modalités d'entrée": "Don Mme J. Pennec  Juillet 1999",
        "Note": "Référencé dans le catalogue Charles X Bugeon réalisé par Michel Ajoux pour l’exposition Charles X Bugeon au château de Noirmoutier"
    },
    {
        "﻿Référence": "4 Fi 61",
        "Auteur": "J. Payen",
        "Titre": "Le Puits de La Rabiette.",
        "Inscription": "Puits de La Rabiette",
        "Objet": "Architecture traditionnelle",
        "Date": "XXe siècle",
        "Lieu": "Ile de Noirmoutier, l’Epine",
        "Technique": "Crayon aquarellé",
        "Support": "papier cartonné, sous verre avec cadre en bois",
        "Dimensions": "64 x 49 cm",
        "Modalités d'entrée": "Don Christophe Corbrejaud de l’Epine",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 62",
        "Auteur": "Marc Aynard",
        "Titre": "Portrait de l’abbé Raimond, l’un des fondateurs de l’AAIN (1885-1969) et fondateur de la chapelle des martyrs à Noirmoutier",
        "Inscription": "",
        "Objet": "Portrait peint devant la croix des martyrs avec en toile de fond les marais salants.",
        "Date": "1951",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "54 x 65 cm",
        "Modalités d'entrée": "Don Raymond Galand",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 63",
        "Auteur": "",
        "Titre": "Bateaux de guerre en rade peut-être de Toulon",
        "Inscription": "",
        "Objet": "marine",
        "Date": "",
        "Lieu": "Toulon ?",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "52 x 43 cm",
        "Modalités d'entrée": "Achat. Provient  de chez  Christophe Corbrejaud de l’Epine",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 64",
        "Auteur": "",
        "Titre": "Paysage de rivière, pont et lavoir",
        "Inscription": "",
        "Objet": "Architecture",
        "Date": "",
        "Lieu": "",
        "Technique": "Aquarelle",
        "Support": "Papier canson",
        "Dimensions": "24 x 31 cm",
        "Modalités d'entrée": "Don",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 65",
        "Auteur": "Florimond Palvadeau (1815 – 1883)",
        "Titre": "La Tour Plantier",
        "Inscription": "F. Palvadeau",
        "Objet": "La Tour plantier",
        "Date": "vers 1870",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "24 x 32,5",
        "Modalités d'entrée": "Achat 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 66",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Femme ramassant des aiguilles de pin dans le Bois de La Chaise",
        "Inscription": "F. Palvadeau",
        "Objet": "Paysage, scène de la vie quotidienne",
        "Date": "Vers 1870",
        "Lieu": "une clairière dans le Bois de La Chaise à Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile marouflée sur carton",
        "Dimensions": "31 x 19 cm",
        "Modalités d'entrée": "Achat 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 67",
        "Auteur": "Florimond Palvadeau",
        "Titre": "Paysage de l’ile de Noirmoutier",
        "Inscription": "",
        "Objet": "Paysage identifié par Vincent Cristofoli comme étant Le Pé du Gouverneur à l’Epine (Lettre aux Amis N° 173)",
        "Date": "Vers 1870",
        "Lieu": "L’Epine à Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "32 x 20 cm",
        "Modalités d'entrée": "Achat 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 68",
        "Auteur": "",
        "Titre": "Plage des Dames",
        "Inscription": "",
        "Objet": "cabines de bains",
        "Date": "",
        "Lieu": "Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Isorel",
        "Dimensions": "40 x 20 cm",
        "Modalités d'entrée": "Achat",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 7",
        "Auteur": "Léon Bopp du Pont (1848-1903)",
        "Titre": "Paysage de bord de mer",
        "Inscription": "Plage sur l’île de Noirmoutier",
        "Objet": "La pointe St Pierre à Noirmoutier",
        "Date": "fin XIXe siècle",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile",
        "Support": "Toile présentée dans un encadrement doré ancien",
        "Dimensions": "60 x 41 cm",
        "Modalités d'entrée": "Achat  Bordeaux, Etude - Mai 2017",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 70",
        "Auteur": "Emile  Libaudière",
        "Titre": "L’église vue du chemin de Ribandon à Noirmoutier",
        "Inscription": "Noirmoutier 1910",
        "Objet": "Paysage",
        "Date": "1910",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "papier",
        "Dimensions": "27,5 x 20 cm",
        "Modalités d'entrée": "Achat 1998",
        "Note": "Lettre aux Amis n°111. Article de Vincent Cristofoli"
    },
    {
        "﻿Référence": "4 Fi 71",
        "Auteur": "Théodore Boulard",
        "Titre": "La pointe Saint Pierre",
        "Inscription": "",
        "Objet": "Paysage",
        "Date": "Milieu XIXe",
        "Lieu": "Noirmoutier",
        "Technique": "Huile",
        "Support": "Bois",
        "Dimensions": "26 x 35 cm",
        "Modalités d'entrée": "",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 72",
        "Auteur": "Jean Vincent-Darasse (1901-1983)",
        "Titre": "Jean Vincent-Darasse. Voiliers au Bois de la Chaise",
        "Inscription": "",
        "Objet": "Marine",
        "Date": "vers 1950",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "toile",
        "Dimensions": "54 x 45 cm",
        "Modalités d'entrée": "offert à Alain Devineau par Mme Clouteau",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 73",
        "Auteur": "Gaussin ?",
        "Titre": "Plage des Dames Noirmoutier",
        "Inscription": "Ile de Noirmoutier Vendée 9/98",
        "Objet": "paysage",
        "Date": "1898",
        "Lieu": "Ile De Noirmoutier",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "35 x 25 cm",
        "Modalités d'entrée": "Achat",
        "Note": "Lettre aux Amis n°111. Article de Vincent Cristofoli"
    },
    {
        "﻿Référence": "4 Fi 74",
        "Auteur": "Gaussin ?",
        "Titre": "L’estacade au Bois de la Chaise",
        "Inscription": "Ile de Noirmoutier Vendée 9/98 Couthuis",
        "Objet": "paysage",
        "Date": "1898",
        "Lieu": "Noirmoutier en l’île",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "35 x 25 cm",
        "Modalités d'entrée": "",
        "Note": "Lettre aux Amis n° 111. Article de Vincent Cristofoli"
    },
    {
        "﻿Référence": "4 Fi 75",
        "Auteur": "René Levrel (1900-1981)",
        "Titre": "Quai Cassard à Noirmoutier",
        "Inscription": "",
        "Objet": "Port de Noirmoutier",
        "Date": "XIXe siècle",
        "Lieu": "Noirmoutier en l’ile",
        "Technique": "Aquarelle",
        "Support": "papier",
        "Dimensions": "30 x 22",
        "Modalités d'entrée": "Achat Nantes étude Couton 2001",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 76",
        "Auteur": "Ludovic Gignoux (1882 - ?)",
        "Titre": "Pierre l’Ermite dans son jardin de la Garennerie",
        "Inscription": "L. Gignoux",
        "Objet": "Mgr Edmond Loutil alias Pierre l’Ermite",
        "Date": "XXe siècle",
        "Lieu": "Noirmoutier en l’Île",
        "Technique": "Huile",
        "Support": "Carton",
        "Dimensions": "35 x 27 cm",
        "Modalités d'entrée": "Achat. Lettre aux amis n°153",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 77",
        "Auteur": "Emile Gautier",
        "Titre": "Chemin à Barbâtre",
        "Inscription": "Emile Gautier",
        "Objet": "Marine",
        "Date": "XXe siècle",
        "Lieu": "Ile de Noirmoutier",
        "Technique": "Huile encadré",
        "Support": "Contre-plaqué",
        "Dimensions": "27 x 22 cm",
        "Modalités d'entrée": "Achat 2009",
        "Note": "Lettre aux amis n°154"
    },
    {
        "﻿Référence": "4 Fi 78",
        "Auteur": "Paul Baudry",
        "Titre": "Paul Baudry : Eros et Psyché",
        "Inscription": "Paul Baudry 1884. Caractères grecs sur le cadre",
        "Objet": "Art",
        "Date": "1884",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile avec encadrement d’origine",
        "Dimensions": "138 x 195 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1995",
        "Note": "Lettre aux Amis n° 99. Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 191"
    },
    {
        "﻿Référence": "4 Fi 79",
        "Auteur": "Ambroise Baudry",
        "Titre": "Le phare du bois de la Chaise",
        "Inscription": "Noirmoutier 10 octobre 1896. Le phare du Bois de la Chaise. Effet du matin",
        "Objet": "Art",
        "Date": "1896",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "41 x 56 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 4"
    },
    {
        "﻿Référence": "4 Fi 8",
        "Auteur": "Guy Dezaunay",
        "Titre": "Les abords de la pointe Saint-Pierre vue des Sableaux",
        "Inscription": "Dezaunay",
        "Objet": "Paysage",
        "Date": "",
        "Lieu": "Ile de Noirmoutier,",
        "Technique": "huile",
        "Support": "contre-plaqué",
        "Dimensions": "53 x 45 cm",
        "Modalités d'entrée": "Achat – 2010",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 80",
        "Auteur": "Ambroise Baudry",
        "Titre": "Le plateau du phare",
        "Inscription": "Noirmoutier sept 1889",
        "Objet": "Paysage",
        "Date": "1889",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "43 x 54 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 5"
    },
    {
        "﻿Référence": "4 Fi 81",
        "Auteur": "Ambroise Baudry",
        "Titre": "Noirmoutier vu du Gaillardin",
        "Inscription": "Noirmoutier 22 octobre 1888 A. Baudry",
        "Objet": "Paysage",
        "Date": "22 octobre 1888",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "26 x 36,5 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 6"
    },
    {
        "﻿Référence": "4 Fi 82",
        "Auteur": "Ambroise Baudry",
        "Titre": "Coin du Bois de la Chaise",
        "Inscription": "à Mimi. Noirmoutier 27 octobre 1889. A. Baudry",
        "Objet": "Paysage",
        "Date": "1889",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "44 x 54 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 7"
    },
    {
        "﻿Référence": "4 Fi 83",
        "Auteur": "Ambroise Baudry",
        "Titre": "Villa Ker Joyeux",
        "Inscription": "Ker Joyeux 2 octobre 1896 A ma petite Hélène",
        "Objet": "Architecture",
        "Date": "1886",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "45 x 34 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 9"
    },
    {
        "﻿Référence": "4 Fi 84",
        "Auteur": "Ambroise Baudry",
        "Titre": "Le plateau du phare",
        "Inscription": "Septembre-octobre 1889 Amb. Baudry",
        "Objet": "Paysage",
        "Date": "1889",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "84 x 102 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Etiquette au dos : The New Gallery. Summer Exhibition 1890. Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 10"
    },
    {
        "﻿Référence": "4 Fi 85",
        "Auteur": "Ambroise Baudry",
        "Titre": "Le chemin de la Blanche",
        "Inscription": "Le chemin de la Blanche. Le matin Septembre 1892 A. Baudry",
        "Objet": "Paysage",
        "Date": "1892",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "48 x 30 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 11"
    },
    {
        "﻿Référence": "4 Fi 87",
        "Auteur": "Ambroise Baudry",
        "Titre": "Anse du cahot",
        "Inscription": "Septembre octobre 1889 A. Baudry",
        "Objet": "Paysage",
        "Date": "1889",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle",
        "Support": "Papier",
        "Dimensions": "95 x 84 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 13"
    },
    {
        "﻿Référence": "4 Fi 88",
        "Auteur": "Ambroise Baudry",
        "Titre": "L’anse du Bois de la Chaise",
        "Inscription": "L’anse du bois de la Chaise à 4h Noirmoutier 10 octobre A.B",
        "Objet": "Paysage",
        "Date": "1896",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Aquarelle encadrée",
        "Support": "Papier",
        "Dimensions": "74 x 57 cm",
        "Modalités d'entrée": "Don Hélène Baudry 1950",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 134"
    },
    {
        "﻿Référence": "4 Fi 89",
        "Auteur": "Louis-Paul Vincent-Darasse dit Paul Vincent-Darasse",
        "Titre": "Les Régates du Bois de la Chaise",
        "Inscription": "Vincent - Darasse 1898",
        "Objet": "Marine",
        "Date": "1898",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Pastel",
        "Support": "Papier",
        "Dimensions": "55 x 33 cm",
        "Modalités d'entrée": "Don Jean Vincent-Darasse 1954",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 17"
    },
    {
        "﻿Référence": "4 Fi 9",
        "Auteur": "Léon Printemps (1871-1945)",
        "Titre": "Coucher de soleil. Référencé E-41",
        "Inscription": "",
        "Objet": "coucher de soleil et bateaux",
        "Date": "1925",
        "Lieu": "Noirmoutier",
        "Technique": "Pastel",
        "Support": "Carton",
        "Dimensions": "27 x 34,5 cm",
        "Modalités d'entrée": "Don  Jacques Noireau 2013",
        "Note": ""
    },
    {
        "﻿Référence": "4 Fi 90",
        "Auteur": "Louis-Paul Vincent-Darasse dit Paul Vincent-Darasse",
        "Titre": "Estacade du Bois de la Chaise",
        "Inscription": "Vincent - Darasse",
        "Objet": "Paysage",
        "Date": "XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "102 x 79 cm",
        "Modalités d'entrée": "Don Jean Vincent-Darasse 1954",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 18"
    },
    {
        "﻿Référence": "4 Fi 91",
        "Auteur": "Louis-Paul Vincent-Darasse dit Paul Vincent-Darasse",
        "Titre": "Marin du Tréport calfatant un bateau",
        "Inscription": "Paul Vincent-Darasse",
        "Objet": "Marine",
        "Date": "Avant 1904",
        "Lieu": "Le Tréport",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "104 x 155 cm",
        "Modalités d'entrée": "",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 - 41"
    },
    {
        "﻿Référence": "4 Fi 94",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Coup de vent",
        "Inscription": "J. Vincent -Darasse",
        "Objet": "Marine",
        "Date": "XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "62 x 82.5 cm",
        "Modalités d'entrée": "Don  Jean Vincent-Darasse 1954",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 15"
    },
    {
        "﻿Référence": "4 Fi 95",
        "Auteur": "Louis-Paul Vincent-Darasse dit Paul Vincent-Darasse",
        "Titre": "Etude des vagues sur une côte rocheuse",
        "Inscription": "",
        "Objet": "Marine",
        "Date": "XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "83 x 65 cm",
        "Modalités d'entrée": "Don de Jean Vincent-Darasse 1954",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 19"
    },
    {
        "﻿Référence": "4 Fi 96",
        "Auteur": "Louis-Paul Vincent-Darasse dit Paul Vincent-Darasse",
        "Titre": "Pêcheurs de sardines",
        "Inscription": "",
        "Objet": "Marine",
        "Date": "XXe siècle",
        "Lieu": "France",
        "Technique": "Huile",
        "Support": "Toile",
        "Dimensions": "78 x 98 cm",
        "Modalités d'entrée": "Don de l’auteur, 1954",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 984 – 20"
    },
    {
        "﻿Référence": "4 Fi 97",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Récolte de pommes de terre",
        "Inscription": "Récolte de pommes de terre. J. Vincent-Darasse 1930",
        "Objet": "Travaux des champs",
        "Date": "1930",
        "Lieu": "Noirmoutier",
        "Technique": "Gouache",
        "Support": "Papier",
        "Dimensions": "77 x 63 cm",
        "Modalités d'entrée": "Don Jean Vincent-Darasse oct. 1980",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 - 22"
    },
    {
        "﻿Référence": "4 Fi 98",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Marais salant et son mulon devant l’église et le château",
        "Inscription": "Vue de Noirmoutier",
        "Objet": "Mulon devant le château et l’église",
        "Date": "1e moitié du XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Gouache",
        "Support": "Papier",
        "Dimensions": "47,5 x 41 cm",
        "Modalités d'entrée": "Don Jean Vincent-Darasse  octobre 1980",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 – 23"
    },
    {
        "﻿Référence": "4 Fi 99",
        "Auteur": "Jean Vincent-Darasse",
        "Titre": "Les marais de Noirmoutier",
        "Inscription": "J. Vincent-Darasse",
        "Objet": "Sauniers tirant le sel",
        "Date": "1e moitié du XXe siècle",
        "Lieu": "Noirmoutier en l’Ile",
        "Technique": "Gouache",
        "Support": "Papier",
        "Dimensions": "47,5 x 41 cm",
        "Modalités d'entrée": "Don Jean Vincent-Darasse",
        "Note": "Inscrit à l’inventaire du Château-Musée de Noirmoutier sous le numéro 994 – 24"
    }
];