var bookDatabase = [
    {
        ID: 1,
        Auteurs: "Auteur 1",
        Titre: "image1.jpg",
        SousTitre: "Sous-titre 1",
        Editeur: "Editeur 1",
        LieuEdition: "Lieu 1",
        DateEdition: "01/01/2023",
        Remarques: "Remarques 1",
        ThemeGeneral: "Thème 1",
        Lieu: "Lieu 1",
        Sujet: "Sujet 1",
        Saisie: "Saisie 1",
        support: "Support 1",
        DateAcquisition: "01/02/2023",
        ModeAcquisition: "Mode 1",
        PrixAquisition: 100,
        FondsOuDons: "Fonds 1"
    },
    {
        ID: 2,
        Auteurs: "Auteur 2",
        Titre: "image2.jpg",
        SousTitre: "Sous-titre 2",
        Editeur: "Editeur 2",
        LieuEdition: "Lieu 2",
        DateEdition: "02/01/2023",
        Remarques: "Remarques 2",
        ThemeGeneral: "Thème 2",
        Lieu: "Lieu 2",
        Sujet: "Sujet 2",
        Saisie: "Saisie 2",
        support: "Support 2",
        DateAcquisition: "02/02/2023",
        ModeAcquisition: "Mode 2",
        PrixAquisition: 150,
        FondsOuDons: "Fonds 2"
    },
	{
        ID: 3,
        Auteurs: "Auteur 1",
        Titre: "image1.jpg",
        SousTitre: "Sous-titre 1",
        Editeur: "Editeur 1",
        LieuEdition: "Lieu 1",
        DateEdition: "01/01/2023",
        Remarques: "Remarques 1",
        ThemeGeneral: "Thème 1",
        Lieu: "Lieu 1",
        Sujet: "Sujet 1",
        Saisie: "Saisie 1",
        support: "Support 1",
        DateAcquisition: "01/02/2023",
        ModeAcquisition: "Mode 1",
        PrixAquisition: 100,
        FondsOuDons: "Fonds 1"
    },
    {
        ID: 4,
        Auteurs: "Auteur 2",
        Titre: "image2.jpg",
        SousTitre: "Sous-titre 2",
        Editeur: "Editeur 2",
        LieuEdition: "Lieu 2",
        DateEdition: "02/01/2023",
        Remarques: "Remarques 2",
        ThemeGeneral: "Thème 2",
        Lieu: "Lieu 2",
        Sujet: "Sujet 2",
        Saisie: "Saisie 2",
        support: "Support 2",
        DateAcquisition: "02/02/2023",
        ModeAcquisition: "Mode 2",
        PrixAquisition: 150,
        FondsOuDons: "Fonds 2"
    }
];
